### ISSUE TITLE
[BUG]: Search-by-typing of programming language may hide desired language

### ISSUE THREAD

**Issue by eyalroz** [compiler-explorer/compiler-explorer#3444] opened 2022-03-14 13:43 UTC
### Describe the bug

When you search for a programming language by typing some of its name, the typed characters appear in a pop-up textbox... which covers the first item(s) on the list of match results. Which in turn will have the desired language if you've typed enough characters from its name.

### Steps to reproduce

Search for the C language...

### Expected behavior

I should see the line with the C languae and be able to select it easily.

### Reproduction link

Not applicable

### Screenshots

Not applicable

**Comment by partouf** [comment] 2022-03-14 13:58
Can you share your browser+version+OS, I cannot reproduce

**Comment by partouf** [comment] 2022-03-14 13:59
In addition; a screenshot of the situation might also be helpful

**Comment by partouf** [comment] 2022-03-14 15:18
> @partouf : What do you mean by "really"? It's hiding the list :-(

No, you can scroll up with your mousewheel, every item will be visible

**Comment by eyalroz** [comment] 2022-03-14 15:29
I may not even have a mousewheel... and besides, I'm using my keyboard. The point is, no combo-box I've every seen behaves like this. It doesn't make sense for typing to happen in a pop-up and to hide the list.

**Comment by eyalroz** [comment] 2022-03-14 18:37
@jeremy-rifkin : But I don't want to scroll, I want to see what's on it while I type.

**Comment by OfekShilon** [comment] 2023-12-24 19:14
This was fixed in some later tomselect release.

**Closed by OfekShilon** 2023-12-24 19:14 UTC
Labels: bug
