### ISSUE TITLE
[BUG] Intermittant rust compilation error

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2685] opened 2021-05-25 17:49 UTC
Visit https://rust.godbolt.org/z/qdTdvvj69 and keep recompiling using the force recompile button. About one in five times we get:

```

#1 with rustc 1.52.0
error: could not copy "/app/output.example.3a1fbbbh-cgu.0.rcgu.s" to "/app/output.s": No such file or directory (os error 2)

error: aborting due to previous error

Compiler returned: 1
```

**Comment by godmar** [comment] 2021-08-01 11:11
I'm seeing this more than 1 in 5 times, particularly if I ask it to add LLVM IR output.

**Comment by bugwelle** [comment] 2021-10-04 07:46
Same happens to me:

https://rust.godbolt.org/z/bqhr7sq4T

```
error: could not copy "/app/output.example.3a1fbbbh-cgu.0.rcgu.s" to "/app/output.s": No such file or directory (os error 2)

error: failed to remove /app/output.example.3a1fbbbh-cgu.0.rcgu.s: No such file or directory (os error 2)

error: aborting due to 2 previous errors
```

**Comment by IsaccBarker** [comment] 2023-01-14 00:44
+1

Sorry this poking this dead issue, but this has steadily increased in frequency for me. Now, I can't get any output, from any compiler version. `mrustc` and and the GCC frontend work fine, however.

**Comment by jeremy-rifkin** [comment] 2023-06-17 22:01
Still happening in 2023
```
error: could not copy "/app/output.example.3a1fbbbh-cgu.0.rcgu.s" to "/app/output.s": No such file or directory (os error 2)

error: aborting due to previous error

Compiler returned: 1
```

**Comment by jeremy-rifkin** [comment] 2023-06-17 22:02
Race condition with temp file cleanup?

**Comment by OfekShilon** [comment] 2024-12-02 08:53
Duplicate of #5987, solved alongside it in https://github.com/OfekShilon/compiler-explorer/commit/135136047665085e91b9f597d6f7ccadcbc10755

**Closed by OfekShilon** 2024-12-02 08:53 UTC
Labels: bug, lang-rust
