### ISSUE TITLE
[BUG]: `No language specified for the editor` notification is obstructed by minimap

### ISSUE THREAD

**Issue by Endilll** [compiler-explorer/compiler-explorer#6353] opened 2024-04-14 11:33 UTC
### Describe the bug

Notification about language not specified for the editor is obstructed by minimap of compiler output.

### Steps to reproduce

1. Visit the attached link
2. Observer the notification in the bottom right corner

### Expected behavior

Notification is not obstructed by minimap.

### Reproduction link

https://godbolt.org/g/Ts3L3P

### Screenshots

![image](https://github.com/compiler-explorer/compiler-explorer/assets/12883766/035ac91d-6783-4c81-940b-3691bca07e42)

### Browser version

Firefox 124

**Comment by jeremy-rifkin** [comment] 2024-04-14 13:07
Thanks for opening this, I think it’s a duplicate of a long standing issue

**Comment by jeremy-rifkin** [comment] 2024-04-14 13:08
#5822

**Closed by jeremy-rifkin** 2024-04-14 13:08 UTC
Labels: bug
