### ISSUE TITLE
[BUG]: noscript edition's output contains color codes

### ISSUE THREAD

**Issue by Alcaro** [compiler-explorer/compiler-explorer#4251] opened 2022-11-06 21:16 UTC
### Describe the bug

See title

### Steps to reproduce

1. https://godbolt.org/noscript/z/56GToKvY9
2. Submit

### Expected behavior

No ansi escape codes. Either tell gcc -fno-diagnostics-color, or postprocess the output to delete them.

### Reproduction link

https://godbolt.org/noscript/z/56GToKvY9

### Screenshots

Expected:
![image](https://user-images.githubusercontent.com/5085186/200195546-84cbadf5-dca6-454f-bc26-601ac870e202.png)
Actual:
![image](https://user-images.githubusercontent.com/5085186/200195408-b44bfa7e-acc5-46ac-a452-577f046212b4.png)

e: duplicate of #4149

**Comment by mattgodbolt** [comment] 2022-11-06 21:20
Duplicate of #4149

**Closed by mattgodbolt** 2022-11-06 21:20 UTC
Labels: bug
