### ISSUE TITLE
[BUG] gcc RTL passes only listed when "Tree Pass" filter is disabled

### ISSUE THREAD

**Issue by topperc** [compiler-explorer/compiler-explorer#2831] opened 2021-07-30 17:33 UTC
**Describe the bug**
When using a gcc compiler The "Select a pass..." dropdown in the "GCC/Tree RTL Output" view does not contain any RTL passes if either of the "Tree Pass" and "IPA Pass" checkboxes are marked along with "RTL Pass" in the Passes dropdown. If only "RTL Pass" has a check then the RTL passes are shown.

**To Reproduce**
Create a C++ source. Select "RISC-V rv64gc gcc 10.2.0" as your compiler.
In the compiler pane, select "Add New.." Choose "GCC/Tree RTL Output". 
Select "Tree Pass" and "RTL Pass" from the Passes drop down.
Observe that the "Select a pass..." drop down does not contain any pass that starts with a number followed by 'r' like 236r.expand.
Clear the "Tree Pass" selection from the Passes drop down.
Observe that the "Select a pass..." drop down now contains passes start with a number followed by 'r'.

**Expected behavior**

**Link**
https://godbolt.org/z/n45sfv7b9

**Screenshots**

**Desktop**

 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by sunmy2019** [comment] 2021-07-31 18:34
And if there are some tree passes missing when the "Tree Pass" checkbox is marked alone. But we can use the search box to find it.

**Comment by sunmy2019** [comment] 2021-07-31 19:22
I found that the drop down list containes  **exactly 50 items**, which should be about 100 items.

Is there anyone familiar with the front end can remove the restriction of 50?

**Comment by sunmy2019** [comment] 2021-07-31 20:22
I never get in touch with JavaScript. But by guessing, I think it is exactly caused by the **TomSelect** here
https://github.com/compiler-explorer/compiler-explorer/blob/508d6045a31d23c4ea639307824c2862bfdd2398/static/panes/gccdump-view.js#L54-L63


And according to the docs: https://tom-select.js.org/docs/
<html>
<body>
maxOptions | The max number of options to display in the dropdown. | int | 50
-- | -- | -- | --
</body>
</html>

This is exactly what we are looking for.

**Comment by partouf** [comment] 2021-08-01 22:55
The fix for this is live

**Closed by partouf** 2021-08-01 22:55 UTC
Labels: bug
