### ISSUE TITLE
[LIB REQUEST] NUMPY and MATPLOTLIB

### ISSUE THREAD

**Issue by jflalle** [compiler-explorer/compiler-explorer#3292] opened 2022-01-25 20:28 UTC
Hi,
Could you add those scientific libraries please ?
Regards.

**Comment by mattgodbolt** [comment] 2022-01-25 20:30
Hi! Do you mean for python? If so, we currently don't have support for any libraries in python, but we'll keep track.  If not python, can you elaborate? Thank you!

**Comment by jflalle** [comment] 2022-01-25 20:33
Hi !

Yes for python.

Thx for your answer.

Regards.

Le 25/01/2022 à 21:30, Matt Godbolt a écrit :

**Comment by RubenRBS** [comment] 2022-10-14 15:04
Closing as duplicate of #3201

**Closed** 2022-10-14 15:05 UTC
Labels: new-libs, lang-python
