### ISSUE TITLE
[BUG]: Missing GCC output with std::atomic and "compile to binary"

### ISSUE THREAD

**Issue by darkmx** [compiler-explorer/compiler-explorer#3221] opened 2021-12-31 16:24 UTC
### Describe the bug

Hi friends.
I was testing the following code with x86-64 gcc 11.2 and the -O3 flag:

```
#include <atomic>

int f(std::atomic<int>& a) {
   return a++;
}
```

and f is not present in the output. https://godbolt.org/z/YdhnhhKP1
![image](https://user-images.githubusercontent.com/19719969/147832041-3e7ef375-dcba-449c-b3aa-58ca4a6a6aa2.png)

If I remove the use of std::atomic (that is, if a becomes an ordinary int), it works. https://godbolt.org/z/MbP1xofEo
![image](https://user-images.githubusercontent.com/19719969/147832145-bf670a64-f1c3-4e6e-ac6f-ce96e61d4275.png)

If I keep std:.atomic but disable the "compile to binary flag", it works. https://godbolt.org/z/vr1ooT3E5

![image](https://user-images.githubusercontent.com/19719969/147832204-6090d0f6-14bd-44b0-8290-3bb0a003bccc.png)

### Steps to reproduce

See above.

### Expected behavior

The "compile to binary" should not hide information. As far as I can see, the flag's main function is to show/hide the generated machine code. I could be wrong.

### Reproduction link

See above.

### Screenshots

See above.

### Operating System

Windows 10

### Browser version

Chrome / Firefox

**Comment by Quuxplusone** [comment] 2021-12-31 17:09
It looks to me like "Compile to binary" really means "_Link_ to binary" — it requires running the linker. (I don't see why it _should_ require linking, but currently it _does_.) So if you give just a single TU with unresolved symbols, you get link errors instead of binary object code: https://godbolt.org/z/7nEr6T6aq

In your case, you gave a TU with no `main`, so Compiler Explorer helpfully added a `main` for you — but their `main` didn't call your `f`, so your `f` was dead code, and at `-O3` the compiler simply optimized it away. Remove `-O3` from the compiler switches, and the `lock xaddl` instruction reappears (in a dead codepath near the bottom of the disassembly).

If there's a feature request here, it's that "Compile to binary" should be able to dump binary straight from a .o file, without needing to link it first.

**Comment by darkmx** [comment] 2021-12-31 17:11
I thought so, but removing std::atomic (and not calling f) does indeed work.

**Comment by dkm** [comment] 2021-12-31 17:18
Yes, currently CE does not support stopping after the assembler, and binary means linking to a correct executable. Stopping after assembler and be able to see relocations info was something I was willing to do in the past. I'll look into that if there's no urgency :)

**Comment by dkm** [comment] 2021-12-31 17:20
Opened here : https://github.com/compiler-explorer/compiler-explorer/issues/3222

**Comment by dkm** [comment] 2022-01-05 20:03
Looks like there is an issue with the assembly parser, as can be seen here :

https://godbolt.org/z/cM1o74zfd

The function f is referenced from main with a call (at addr `401106`) but the assembly is only displayed from main (addr `401125`). I guess it's because `0000000000001129 <f(std::atomic<int>&)>:` is not detected as a function start.
Local run shows (with debug added server side, and different addresses):
```
debug: asm line : 0000000000001129 <f(std::atomic<int>&)>:
debug: asm line : f(std::atomic<int>&):
debug: asm line : /tmp/compiler-explorer-compiler202205-653865-1umwyql.zwuy/example.cpp:4
debug: asm line :     1129:     55                                                      push   rbp
debug: asm line :     112a:     48 89 e5                                                mov    rbp,rsp
debug: asm line :     112d:     48 83 ec 10                                             sub    rsp,0x10
debug: asm line :     1131:     48 89 7d f8                                             mov    QWORD PTR [rbp-0x8],rdi
debug: asm line : /tmp/compiler-explorer-compiler202205-653865-1umwyql.zwuy/example.cpp:5
debug: asm line :     1135:     48 8b 45 f8                                             mov    rax,QWORD PTR [rbp-0x8]
debug: asm line :     1139:     be 00 00 00 00                                          mov    esi,0x0
debug: asm line :     113e:     48 89 c7                                                mov    rdi,rax
debug: asm line :     1141:     e8 6e 00 00 00                                          call   11b4 <std::__atomic_base<int>::operator++(int)>
debug: asm line : /tmp/compiler-explorer-compiler202205-653865-1umwyql.zwuy/example.cpp:6
debug: asm line :     1146:     c9                                                      leave
debug: asm line :     1147:     c3                                                      ret
debug: asm line :
debug: asm line : 0000000000001148 <main>:
debug:  func: main, is user: true
debug: asm line : main():
debug: asm line : /tmp/compiler-explorer-compiler202205-653865-1umwyql.zwuy/example.cpp:8
debug: asm line :     1148:     55                                                      push   rbp
debug: asm line :     1149:     48 89 e5                                                mov    rbp,rsp
debug: asm line :     114c:     48 83 ec 20                                             sub    rsp,0x20
debug: asm line :     1150:     89 7d ec                                                mov    DWORD PTR [rbp-0x14],edi
debug: asm line :     1153:     48 89 75 e0                                             mov    QWORD PTR [rbp-0x20],rsi
debug: asm line : /tmp/compiler-explorer-compiler202205-653865-1umwyql.zwuy/example.cpp:9
debug: asm line :     1157:     8b 55 ec                                                mov    edx,DWORD PTR [rbp-0x14]
debug: asm line :     115a:     48 8d 45 fc                                             lea    rax,[rbp-0x4]
debug: asm line :     115e:     89 d6                                                   mov    esi,edx
debug: asm line :     1160:     48 89 c7                                                mov    rdi,rax
debug: asm line :     1163:     e8 10 00 00 00                                          call   1178 <std::atomic<int>::atomic(int)>
debug: asm line : /tmp/compiler-explorer-compiler202205-653865-1umwyql.zwuy/example.cpp:10
debug: asm line :     1168:     48 8d 45 fc                                             lea    rax,[rbp-0x4]
debug: asm line :     116c:     48 89 c7                                                mov    rdi,rax
debug: asm line :     116f:     e8 b5 ff ff ff                                          call   1129 <f(std::atomic<int>&)>
```

I'm currently hacking around this for #3232, so will fix it in the same change.

**Comment by dkm** [comment] 2022-01-15 21:16
@darkmx I think we can close this issue. As explained by @Quuxplusone , that's not a bug, simply a side effect of how CE implements the "compile to binary".

Do not hesitate to reopen if you think it should not have been closed :)

**Closed by dkm** 2022-01-15 21:16 UTC
Labels: bug

**Comment by darkmx** [comment] 2022-01-15 22:48
From what @Quuxplusone said, I understood that dead-code elimination was the culprit, yet dead-code elimination doesn't explain why the asm of `f(int&)` did appear in the output while the asm `f(atomic<int>&)` did not, since both of them are dead-code as there is no `main` to call any of them: https://godbolt.org/z/Tx7G6bfco. @dkm based on your previous comment, I thought there was an issue to fix (in the parser, being able to detect the function start). Now I am at a loss :(

**Comment by partouf** [comment] 2022-01-15 23:02
> From what @Quuxplusone said, I understood that dead-code elimination was the culprit, yet dead-code elimination doesn't explain why the asm of `f(int&)` did appear in the output while the asm `f(atomic<int>&)` did not, since both of them are dead-code as there is no `main` to call any of them: https://godbolt.org/z/Tx7G6bfco. @dkm based on your previous comment, I thought there was an issue to fix (in the parser, being able to detect the function start). Now I am at a loss :(

The issue in the link here will be fixed when https://github.com/compiler-explorer/compiler-explorer/issues/3235 goes live (its not yet) - you can work around it by unchecking Output -> Demangle Identifiers

**Comment by darkmx** [comment] 2022-01-15 23:06
Oh ok. Then this issue may be marked as duplicate of #3235, so closing this is indeed correct.

**Comment by dkm** [comment] 2022-01-16 07:40
Sorry I wasn't clear. Your initial report is not a bug and @Quuxplusone explained exactly was is happening (no main in your code, CE inserts a dummy one without any call to f, f is being removed). There's nothing to fix in CE about this, everything is working as expected.
To get your expected result, you can fix your code to have a main function that call your f function. That's what I did above, and that triggers a bug #3235 in the ASM parser. Fixing this bug won't change anything to your initial code though.
You can check this by simply doing it locally (copy paste your code in a file, and an empty main, run `gcc -o test test.cc`, disasm with `objdump -d test`), and you should also observe that f is missing.

Another solution will be available when https://github.com/compiler-explorer/compiler-explorer/pull/3232  is ready.
