### ISSUE TITLE
Replace the request library

### ISSUE THREAD

**Issue by jeremy-rifkin** [compiler-explorer/compiler-explorer#4537] opened 2023-01-04 18:29 UTC
Since [request][-1] is deprecated we may as well replace it, [node-fetch][1] is a possible alternative

[-1]: https://github.com/request/request
[1]: https://github.com/node-fetch/node-fetch

**Comment by RubenRBS** [comment] 2023-01-07 00:19
I dream about a world were new js features are common to everyone so we could also eventually use the fetch api client side at some point

**Comment by gautam1168** [comment] 2023-02-12 09:31
It is not stable yet, but they are adding a browser compatible fetch api in nodejs.

https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch

**Comment by OfekShilon** [comment] 2023-10-28 20:00
The `request` team themselves wrote down [some possible replacements](https://github.com/request/request/issues/3143). Some extra data on that list (collected Oct 28 2023):

 1. [node-fetch](https://github.com/node-fetch/node-fetch) : 8.5K stars, last commit Jul 25 (despite 31 open PRs).
 2. [bent](https://github.com/node-fetch/node-fetch): 2.2K stars, last commit Oct 10 2020.
 3. [got](https://github.com/node-fetch/node-fetch): 13.5K stars, last commit 2w ago.
 4. [make-fetch-happen](https://github.com/npm/make-fetch-happen): 170 stars, last commit Sep 18.
 5. [axios](https://github.com/axios/axios): 102K stars, last commit 2d ago. 
 6. [unfetch](https://github.com/developit/unfetch): 5.6K stars, last commit Jan 3.
 7. [superagent](https://github.com/ladjs/superagent): 16.4K stars, last commit Aug 30.
 8. [tiny-json-http](https://github.com/brianleroux/tiny-json-http): 166 stars, last commit Mar 30.
 9. [needle](https://github.com/tomas/needle): 1.6K stars, last commit Nov 17 2022.
 10. [urllib](https://github.com/node-modules/urllib): 713 stars, last commit Sep 21.

`axios` seems not only by far the most popular, but also the most active. When the 'request' guys collected bundle size in Apr 2019 it was the 4th lightest, don't know if that still holds.  It's license is MIT.

I'd be happier with a replacement that's backed by some company, but AFAICT none of these are.

If you agree I'll try to prepare a PR replacing `request` with `axios`. It should be very similar.

**Comment by jeremy-rifkin** [comment] 2023-10-29 22:33
Thanks for looking into the alternatives, I think any of axios, node-fetch, or got sound good to me. Do any stand out in terms of the interface they provide?

**Comment by partouf** [comment] 2023-10-29 22:48
I still think we should stick with request as long as it's not being announced to be deleted or something. Http is not a trivial thing, but it's also not as if it needs extra features, so if it's done it's done. And request has been serving us pretty well so far.

**Comment by OfekShilon** [comment] 2023-10-30 09:39
<semi-philosophical 2c>
 1. Things change and maintenance is always needed. Dependent libraries, browsers and [even standards](https://en.wikipedia.org/wiki/HTTP/2) evolve and/or have bugs.
 2. An author's notice of library deprecation means they want to let it die and move on - respecting it and not holding them back is just good citizenship.
 3. Keeping a project warning-free has its own value - occasionally warnings indicate real problems and growing accustomed to ignoring warnings masks these. This goes for the various linters used in CE as well as for deprecation warnings.

</semi-philosophical 2c>

All that said I think this isn't a big decision and agree there is currently no *technical* reason to migrate from `request`. Also I had no idea this issue was controversial, if it is - I'll be on my way doing other stuff.

**Comment by partouf** [comment] 2023-10-30 15:29
> All that said I think this isn't a big decision and agree there is currently no _technical_ reason to migrate from `request`. Also I had no idea this issue was controversial, if it is - I'll be on my way doing other stuff.

It's not so much controversial, I think multiple people wanted to do this as well.
I'm just not really in the mood currently to debug strange issues that come up as a result of switching.

**Comment by OfekShilon** [comment] 2024-02-09 21:59
Closing as duplicate of #5289

**Closed by OfekShilon** 2024-02-09 21:59 UTC
Labels: enhancement, low priority, request
