### ISSUE TITLE
[BUG]: shared link from ipad safari doesn't remember which tab is open and also changes order of tabs

### ISSUE THREAD

**Issue by hanickadot** [compiler-explorer/compiler-explorer#6713] opened 2024-07-22 10:18 UTC
### Describe the bug

When I have set my interface with code on left and two tabs on right, where I want to show only error message from compiler, shared link from ipad (can't test on other system for now) sometimes doesn't remember setting which tabs to show, and also it reorders tabs.

BEFORE sending link:
 
![IMG_0094](https://github.com/user-attachments/assets/1eb6b0b6-ae8c-43af-b058-4cb351345f95)

AFTER opening link:

![IMG_0093](https://github.com/user-attachments/assets/efada88b-a2e5-43e3-aa8d-b29e52c66336)

(notice the different order)

This lead to confusion at CE's discord: https://discord.com/channels/763778740345765900/764131393332314123/1264674567910195362

### Steps to reproduce

1. set up interface with multiple tabs on right, select non-first
2. share link
3. open the link

### Expected behavior

order of tabs will stay same and same tab is open as expected

### Reproduction link

Not applicable

### Screenshots

in description

### Operating System

latest ipad os

### Browser version

safari

**Comment by OfekShilon** [comment] 2024-08-22 13:19
Hi @hanickadot and thanks for reporting this!

When deserializing the layout from a shared link, the component we use (`GoldenLayout`) by default does some adjustment to the device. Technically this *can* be controlled via [the undocumented setting](https://github.com/golden-layout/golden-layout/blob/95af36d1e4c596696483c5353d32ae71886b999c/src/ts/config/config.ts#L782-L785) `responsiveMode`, but in general I think this makes sense. 
So I think it is reasonable to expect diffs in layout when sharing from ipad to PC. I couldn't reproduce the problem for PC-to-PC sharing. Do you have a repro?

**Comment by OfekShilon** [comment] 2024-09-02 15:46
Closing for now, will happily re-open if new info emerges

**Closed by OfekShilon** 2024-09-02 15:46 UTC
Labels: bug
