### ISSUE TITLE
[BUG]  Compilation failed: undefined

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#2802] opened 2021-07-23 21:36 UTC
When compiling this code: https://gcc.godbolt.org/z/bsMc64ccz

The compilation error is hidden (you can see it in the resutls), but the report is "`<Compilation failed: undefined>"`

**Comment by Alcaro** [comment] 2021-07-23 21:42
Reduced testcase: https://gcc.godbolt.org/z/Kx1WTWh6e

Does not reproduce if I replace it with [some random smaller file](https://raw.githubusercontent.com/compiler-explorer/compiler-explorer/main/.gitattributes). I don't know if it reacts to file size, file type, some specific substring of that file, or something else.

**Comment by Alcaro** [comment] 2021-07-23 22:12
Further reduced:
```
#line 200
x
```
https://gcc.godbolt.org/z/G4KnWY3nT

**Comment by RubenRBS** [comment] 2021-07-23 22:15
I've stopped the site from not working at all because of this for now. 7427b93 avoids showing undefined in the UI, and 209c8f4 brings the output out.
As suspected, it's a problem when we try to map non expanded #includes to what the compiler is ultimately seeing

**Comment by partouf** [comment] 2021-08-01 22:52
We can close this one in favor of #2803 then

**Closed by partouf** 2021-08-01 22:52 UTC
Labels: bug
