### ISSUE TITLE
[BUG]: mips64 (el) GCC appears to actually be 32-bit

### ISSUE THREAD

**Issue by GabrielRavier** [compiler-explorer/compiler-explorer#5917] opened 2023-12-26 22:56 UTC
### Describe the bug

The MIPS64 EL compilers (e.g. "mips64 (el) gcc 13.2.0") appear to not actually be 64-bit, instead emitting 32-bit MIPS code.

### Steps to reproduce

1. Visit godbolt.org
2. Use the "mips64 (el) gcc 13.2.0" compiler (or any other "mips64 (el) gcc")
3. Observe the output being 32-bit code instead of 64-bit code (in particular visible when using e.g. `void *`, `size_t` or 64-bit arithmetic in general - which can easily be compared with the "mips64 gcc" (not el) compilers, which do emit 64-bit code

### Expected behavior

I expected 64-bit code to be emitted instead of 32-bit code.

### Reproduction link

https://godbolt.org/z/oPPv7Gzn5

### Screenshots

Not applicable

### Operating System

Fedora release 39 (Thirty Nine)

### Browser version

Mozilla Firefox 121.0

**Comment by dkm** [comment] 2023-12-27 09:15
Configs look good though:

```
mips64el-12.1.0.config
181:CT_ARCH_LE=y
188:CT_ARCH_64=y

mips64el-12.2.0.config
184:CT_ARCH_LE=y
191:CT_ARCH_64=y

mips64el-12.3.0.config
187:CT_ARCH_LE=y
194:CT_ARCH_64=y

mips64el-13.2.0.config
187:CT_ARCH_LE=y
194:CT_ARCH_64=y

mips64el-13.1.0.config
187:CT_ARCH_LE=y
194:CT_ARCH_64=y

mips64el-4.9.4.config
169:CT_ARCH_LE=y
176:CT_ARCH_64=y

mips64el-9.5.0.config
169:CT_ARCH_LE=y
176:CT_ARCH_64=y

mips64el-5.5.0.config
169:CT_ARCH_LE=y
176:CT_ARCH_64=y
```

**Comment by dkm** [comment] 2023-12-27 11:05
https://godbolt.org/z/Kqn8MKhYn

![image](https://github.com/compiler-explorer/compiler-explorer/assets/87603/72ea4c9b-2a60-4e84-9a19-3e26ac52fa2a)

Pointer is as expected 8 vs 4, endianess is also as expected.

But size_t and alignment for the 64el are smaller (4 vs 8, 16 vs 32) than 64, which is puzzling.

**Comment by GabrielRavier** [comment] 2023-12-27 22:47
I can say mips64el seems to also clearly be using 32-bit operations to implement 64-bit operations (e.g. `a64BitNumber < another64BitNumber` resolves to like 10 instructions that do the comparison with 32-bit operations) whereas mips64 (big endian) does it in a single `slt`

**Comment by dkm** [comment] 2024-01-05 13:25
Hmmm, wondering if that's not an ABI issue. The mips64el toolchain are configured for the o32 ABI, which looks strange.
The mips64 is targeting the n64 ABI.

@GabrielRavier do you have any knowledge around that? Is mips64el with o32 a valid setup? Or is it non-sense and it should be fixed with the n64 ABI?

**Comment by GabrielRavier** [comment] 2024-01-05 13:41
I don't know enough about MIPS to be able to say whether it's a configuration one could use in the real world or not, but it definitely seems at the very least quite rare. For instance, Clang when using `-target mips64el` seems to use the N64 ABI by default, the mips64el port of Debian claims to use the N64 ABI without any note that this is atypical or a choice of particular importance and the cross-compiler for MIPS64EL I can install on my Fedora machine seems to use the N64 ABI by default.

Also, I'd say O32 seems like a pretty odd choice anyway because it's defined as being for 32-bit instructions - there's no provision in it for 64-bit instructions and it requires the processor to run in 32-bit mode, so regardless of how much sense it makes it seems pretty useless for the purposes of looking at assembly output for a 64-bit processor (especially when the corresponding 32-bit toolchain that emits 32-bit code is also available).

**Comment by dkm** [comment] 2024-01-05 14:06
Ok, thanks for looking a bit into this.
I'm asking because if this particular setup is non-sense, we can fix it. If it can makes sense, then maybe we should not fix it directly as the codegen will be changed for already existing shared links.

I guess we could change the setting... But I'll ask before taking this decision

**Comment by dkm** [comment] 2024-01-05 17:40
Setting the ABI to n64 indeed seems to fix this. I get similar output as for mips64:
```
g:
        jr      $31
        slt     $2,$4,$5
```

**Comment by Alcaro** [comment] 2024-01-05 18:02
Make sure to check that you didn't accidentally swap the endian, using something like https://godbolt.org/z/43q5rYnzq

**Comment by dkm** [comment] 2024-01-06 08:55
```
square:
        jr      $31
        li      $2,2                    # 0x2
cube:
        jr      $31
        li      $2,8                    # 0x8
```

Looks good :+1:

**Comment by dkm** [comment] 2024-01-15 21:23
Rebuilt most compilers... only 64el 13.2 and 13.1 are not happy.
```
 199   │ 2024-01-15T20:44:51.4758686Z [INFO ]  =================================================================
 200   │ 2024-01-15T20:44:51.4766803Z [INFO ]  Installing GMP for host
 201   │ 2024-01-15T20:44:51.4796778Z [EXTRA]    Configuring GMP
 202   │ 2024-01-15T20:44:53.5513580Z [ERROR]    configure: error: C++ compiler not available, see config.log for details
 203   │ 2024-01-15T20:44:53.5707377Z [ERROR]  
 204   │ 2024-01-15T20:44:53.5716779Z [ERROR]  >>
 205   │ 2024-01-15T20:44:53.5724581Z [ERROR]  >>  Build failed in step 'Installing GMP for host'
 206   │ 2024-01-15T20:44:53.5732373Z [ERROR]  >>        called in step '(top-level)'
 207   │ 2024-01-15T20:44:53.5739989Z [ERROR]  >>
 208   │ 2024-01-15T20:44:53.5748698Z [ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@377]
 209   │ 2024-01-15T20:44:53.5758630Z [ERROR]  >>        called from: do_gmp_backend[scripts/build/companion_libs/100-gmp.sh@128]
 210   │ 2024-01-15T20:44:53.5766991Z [ERROR]  >>        called from: do_gmp_for_host[scripts/build/companion_libs/100-gmp.sh@58]
 211   │ 2024-01-15T20:44:53.5775627Z [ERROR]  >>        called from: do_companion_libs_for_host[scripts/build/companion_libs.sh@36]
 212   │ 2024-01-15T20:44:53.5784011Z [ERROR]  >>        called from: main[scripts/crosstool-NG.sh@707]
 213   │ 2024-01-15T20:44:53.5804155Z [ERROR]  >>
 214   │ 2024-01-15T20:44:53.5815050Z [ERROR]  >>  For more info on this error, look at the file: 'build.log'
 215   │ 2024-01-15T20:44:53.5824382Z [ERROR]  >>  There is a list of known issues, some with workarounds, in:
 216   │ 2024-01-15T20:44:53.5834610Z [ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
```

Probably something stupid.

**Comment by dkm** [comment] 2024-01-17 07:37
> Rebuilt most compilers... only 64el 13.2 and 13.1 are not happy.
> 
> ```
>  199   │ 2024-01-15T20:44:51.4758686Z [INFO ]  =================================================================
>  200   │ 2024-01-15T20:44:51.4766803Z [INFO ]  Installing GMP for host
>  201   │ 2024-01-15T20:44:51.4796778Z [EXTRA]    Configuring GMP
>  202   │ 2024-01-15T20:44:53.5513580Z [ERROR]    configure: error: C++ compiler not available, see config.log for details
>  203   │ 2024-01-15T20:44:53.5707377Z [ERROR]  
>  204   │ 2024-01-15T20:44:53.5716779Z [ERROR]  >>
>  205   │ 2024-01-15T20:44:53.5724581Z [ERROR]  >>  Build failed in step 'Installing GMP for host'
>  206   │ 2024-01-15T20:44:53.5732373Z [ERROR]  >>        called in step '(top-level)'
>  207   │ 2024-01-15T20:44:53.5739989Z [ERROR]  >>
>  208   │ 2024-01-15T20:44:53.5748698Z [ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@377]
>  209   │ 2024-01-15T20:44:53.5758630Z [ERROR]  >>        called from: do_gmp_backend[scripts/build/companion_libs/100-gmp.sh@128]
>  210   │ 2024-01-15T20:44:53.5766991Z [ERROR]  >>        called from: do_gmp_for_host[scripts/build/companion_libs/100-gmp.sh@58]
>  211   │ 2024-01-15T20:44:53.5775627Z [ERROR]  >>        called from: do_companion_libs_for_host[scripts/build/companion_libs.sh@36]
>  212   │ 2024-01-15T20:44:53.5784011Z [ERROR]  >>        called from: main[scripts/crosstool-NG.sh@707]
>  213   │ 2024-01-15T20:44:53.5804155Z [ERROR]  >>
>  214   │ 2024-01-15T20:44:53.5815050Z [ERROR]  >>  For more info on this error, look at the file: 'build.log'
>  215   │ 2024-01-15T20:44:53.5824382Z [ERROR]  >>  There is a list of known issues, some with workarounds, in:
>  216   │ 2024-01-15T20:44:53.5834610Z [ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
> ```
> 
> Probably something stupid.

again caused by ct-ng not liking LD_LIBRARY_PATH being overloaded...

**Comment by dkm** [comment] 2024-01-17 10:22
All compilers rebuilt. Need to reinstall

**Comment by dkm** [comment] 2024-01-17 21:54
Your reproducer is now looking good. What do you think @GabrielRavier ?
FTR, ![image](https://github.com/compiler-explorer/compiler-explorer/assets/87603/6dcf8a77-bdd7-4522-aa3c-0f34d298e18a)

**Comment by dkm** [comment] 2024-01-19 10:36
I'll go ahead and close it. Reopen if you notice anything suspicious

**Closed by dkm** 2024-01-19 10:36 UTC
Labels: bug

**Comment by GabrielRavier** [comment] 2024-01-26 11:43
I hadn't been able to look at this until now, but I can say it looks good to me too

**Comment by dkm** [comment] 2024-01-26 15:42
Thanks for checking!
