### ISSUE TITLE
"null" in icc output

### ISSUE THREAD

**Issue by sirzooro** [compiler-explorer/compiler-explorer#1220] opened 2018-12-12 16:59 UTC
I do not know if it is problem with Compiler Explorer at https://godbolt.org/ or bug in icc. I tried to compile this code using x86_64 icc 19.0.1 with options -O3 -march=skylake-avx512:

```c
#include <immintrin.h>

__mmask8 test(__mmask8 m)
{
    __mmask8 m2 = _kand_mask8(m, 3);
    return m2;
}
```

It generated this assembly code:

```asm
test(unsigned char):
        vkmovb    k0, edi                                       #5.19
        null      k1, 3                                         #5.19
        kandb     k2, k0, k1                                    #5.19
        vkmovb    eax, k2                                       #5.19
        ret                                                     #6.12
```

There is strange `null` instruction there. Please take a look on this.

**Comment by mattgodbolt** [comment] 2018-12-12 18:13
https://godbolt.org/z/GKv7nb is an example demonstrating this. if we dump the binary (see the bottom window):

```
test(unsigned char):
 kmovd %edi,%k0
 roll $0x0,(%rbx)
 kandb %k1,%k0,%k2
 kmovd %k2,%eax
 retq 
```

**Comment by mattgodbolt** [comment] 2018-12-12 18:14
Seems it's an `icc` bug:

```
ubuntu@admin-node ~> cat > /tmp/test.cc
#include <immintrin.h>

__mmask8 test(__mmask8 m)
{
    __mmask8 m2 = _kand_mask8(m, 3);
    return m2;
}
ubuntu@admin-node ~> /opt/compiler-explorer/intel-2019.1/bin/icc -S /tmp/test.cc -O3 -march=skylake-avx512 -o -
        .file "test.cc"
        .text
..TXTST0:
.L_2__routine_start__Z4testh_0:
# -- Begin  _Z4testh
        .text
       .align    16,0x90
        .globl _Z4testh
_Z4testh:
# parameter 1: %edi
..B1.1:
        .cfi_startproc
        .cfi_personality 0x3,__gxx_personality_v0
..___tag_value__Z4testh.1:
..L2:

        vkmovb    %edi, %k0
        null      $3, %k1
        kandb     %k1, %k0, %k2
        vkmovb    %k2, %eax
        ret       
        .align    16,0x90
        .cfi_endproc
        .type   _Z4testh,@function
        .size   _Z4testh,.-_Z4testh
..LN_Z4testh.0:
        .data
# -- End  _Z4testh
        .data
        .section .note.GNU-stack, ""
# End
```

**Comment by mattgodbolt** [comment] 2018-12-12 19:11
I filed a bug with Intel: ref 03997020

**Comment by sirzooro** [comment] 2018-12-12 19:23
Thanks for reporting it to Intel.

**Comment by mattgodbolt** [comment] 2018-12-13 13:54
From Intel:

I have reproduced this bug and escalated (CMPLRIL0-30914). Should be corrected in the upcoming compiler updates.

I will notify you once it is fixed.

**Comment by mattgodbolt** [comment] 2019-11-12 03:47
I've pinged Intel on this again, I've not heard anything.

**Comment by jeremy-rifkin** [comment] 2023-03-12 23:53
Looks like this is fixed in newer versions of ICC. Do we want to leave this open?

**Comment by mattgodbolt** [comment] 2023-03-12 23:57
I'm delighted to close anything where we can...please do!

**Comment by jeremy-rifkin** [comment] 2023-03-13 00:01
Will go ahead and close for now

**Closed by jeremy-rifkin** 2023-03-13 00:01 UTC
Labels: question, waiting
