### ISSUE TITLE
[BUG]: compile-to-binary is broken for NVCC compilations.

### ISSUE THREAD

**Issue by Artem-B** [compiler-explorer/compiler-explorer#3281] opened 2022-01-21 22:10 UTC
### Describe the bug

https://godbolt.org/z/EsEva3x8E

None of the CUDA compilations show anything when compile to binary option is selected.
Compilation with CUDA-11 fails with an error somewhere in disassembly parsing inside of CE:

```
Internal Compiler Explorer error: TypeError: Cannot read properties of undefined (reading 'split')
    at SassAsmParser.processBinaryAsm (/infra/.deploy/lib/asm-parser.js:619:54)
    at SassAsmParser.processAsm (/infra/.deploy/lib/asm-parser.js:264:41)
    at SassAsmParser.process (/infra/.deploy/lib/asm-parser.js:656:21)
    at NvccCompiler.processAsm (/infra/.deploy/lib/base-compiler.js:1720:25)
    at NvccCompiler.afterCompilation (/infra/.deploy/lib/base-compiler.js:1681:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /infra/.deploy/lib/base-compiler.js:1655:20
    at async run (/infra/.deploy/node_modules/p-queue/dist/index.js:163:29)
Compiler returned: -1
```

Clang's compile-to-binary works OK.

### Steps to reproduce

https://godbolt.org/z/EsEva3x8E

### Expected behavior

No crashes and CE showing the disassembly.

### Reproduction link

https://godbolt.org/z/EsEva3x8E

### Screenshots

Not applicable
![image](https://user-images.githubusercontent.com/526795/150606755-69752b9a-39ce-4332-8328-f8b0590ca4d4.png)

**Comment by mattgodbolt** [comment] 2022-01-21 22:11
Duplicate of #3276  - but this has plenty of extra info. Thanks for taking the time to report!

**Closed by mattgodbolt** 2022-01-21 22:11 UTC
Labels: bug
