### ISSUE TITLE
[BUG] OPT for ICX not working

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/compiler-explorer#2489] opened 2021-03-11 23:34 UTC
You are right--not working on godbolt.org.

I synced my main branch with upstream and it works locally. I have to edit my c++.defaults.properties to enable c++, but I am just using the same info as c++.amazon

Do you have a way to inspect the live system to verify that base-compiler.js has the change?

_Originally posted by @rscohn2 in https://github.com/compiler-explorer/compiler-explorer/issues/2488#issuecomment-797120317_

**Comment by rscohn2** [comment] 2021-03-12 12:21
The problem is that LD_LIBRARY_PATH is not being set when it does icx --help to see if the argument is supported.  It looks like I need to modify https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/base-compiler.js#L128 to pass through ldPath in the options parameter.

I would like to offer another solution. For another project that was installing the compiler, they asked me to add a little post-install code that did a patchelf and set the RPATH on the compiler binary and some shared libraries so LD_LIBRARY_PATH was not needed to invoke the compiler. In shell it would be:
patchelf --set-rpath /opt/compiler-explorer/intel-cpp-2021.1.2.63/compiler/latest/linux/compiler/lib/intel64_lin/ /opt/compiler-explorer/intel-cpp-2021.1.2.63/compiler/latest/linux/compiler/bin/icx

and the same for a few more .so's.

Note that I have asked the developer who works on the compiler driver to put rpath in the original package so setting LD_LIBRARY_PATH will not be necessary. I am not sure if it will be in the next release.

**Comment by rscohn2** [comment] 2021-03-12 12:25
This is the patchelf solution in another project: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/intel-oneapi-compilers/package.py#L63

patchelf is not installed by default on most distro's. On ubuntu you need:
sudo apt-get install patchelf

**Comment by mattgodbolt** [comment] 2021-03-12 12:54
`patchelf` can work I guess: we use it in other cases and have it available at `/opt/compiler-explorer/patchelf-0.8/src/patchelf`

We try our best to _not_ hardcode paths into our executables but this might be acceptable. I tend to use `$ORIGIN`-based rpaths when I must, maybe we can do the same here.

I worry about "and the same for a few more .so's" - which ones do you think we need?

**Comment by rscohn2** [comment] 2021-03-12 13:04
I can use $ORIGIN. It would patch all the files in: compiler/lib/intel64_lin, compiler/lib/intel64, bin. patchelf will only patch files that can have an RPATH so I do * in those directories. Let me know if you want patchelf or to continue to use ldPath.

**Comment by mattgodbolt** [comment] 2021-03-12 13:10
Great stuff: let's go with patchelf. Our installation setup has (limited) support for rpath-setting, at least when we install the `rust` compilers: https://github.com/compiler-explorer/infra/blob/0c3793f93248642df6d05a0eca81e5e23346e08b/bin/lib/installation.py#L273 for example; or we can hardcode it in the installers at https://github.com/compiler-explorer/infra/blob/0c3793f93248642df6d05a0eca81e5e23346e08b/bin/yaml/cpp.yaml#L372-L405 and reinstall the compilers...

@partouf any thoughts on what you prefer?  We have precedent in `rust`, though it might also be nice to fix up the library path during `--help` too.

**Comment by partouf** [comment] 2021-03-12 13:47
patching is always an option, but I'd rather correct the code just so we're not confused about this in the future with other compilers

**Comment by rscohn2** [comment] 2021-03-12 14:15
I will correct the code. For reference, this is the minimal patch that works. It will also work to replace the binaries with *.

```
for f in compiler/linux/compiler/lib/intel64/libimf.so; do patchelf --set-rpath '$ORIGIN' $f; done
for f in compiler/linux/bin/{icx,icpx,clang,clang++}; do patchelf --set-rpath '$ORIGIN/../compiler/lib/intel64' $f; done
```

**Closed** 2021-03-12 14:32 UTC
Labels: bug
