### ISSUE TITLE
CParser compiler

### ISSUE THREAD

**Issue by nkindt** [compiler-explorer/compiler-explorer#1124] opened 2018-10-22 10:28 UTC
Suggestion to add cparser to the list. Pretty good optimizing compiler, features some novel/aggressive optimization techniques and multiple backends:
https://github.com/libfirm/cparser

Usage example (dropin replacement for gcc):
https://pp.ipd.kit.edu/firm/Download.html

**Comment by matsjla** [comment] 2022-01-28 23:47
Duplicate of #425

**Closed by matsjla** 2022-01-28 23:47 UTC
Labels: new-compilers, lang-c
