### ISSUE TITLE
MSVC is missing (only WINE versions)

### ISSUE THREAD

**Issue by bernd5** [compiler-explorer/compiler-explorer#1929] opened 2020-04-22 11:00 UTC
The dropdown menu does not contain the msvc compilers anymore - is it a bug?
(They have been there - up to version 19.24)

It is great to have multiple compilers available to check conformance ....

@mattgodbolt: btw. great job, thank you!

**Comment by Yankes** [comment] 2020-04-22 17:22
Same issue there, I used it to check if my complex code do not break any supported compilers by my project, now I can't check it now because version of VS avaialbe are to old for my needs (they have too many errors in C++17).

**Comment by mattgodbolt** [comment] 2020-04-22 18:08
Microsoft's site (which we back on to) is down: www.godbolt.ms

I've contated Microsoft about this. (CC @strega-nil )

**Comment by mattgodbolt** [comment] 2020-04-22 18:08
Oh! It's actually back...we should recover shortly

**Comment by mattgodbolt** [comment] 2020-04-22 18:12
Will bounce the site to pick up: after a certain number of tries we give up. We'll have to improve this :

**Comment by mattgodbolt** [comment] 2020-04-22 18:22
Ah: no. The compiler list on godbolt.ms is empty: https://www.godbolt.ms/api/compilers/c++

**Comment by mattgodbolt** [comment] 2020-04-22 18:25
It's sporadic. Hopefully it will be back. MS got back to me: they're super busy both in terms of people power available and infrastructure due to the COVID crisis. So, some patience is appreciated! Thanks!

**Comment by RabsRincon** [comment] 2020-04-22 18:43
Hi! For the msvc compilers we rely on Microsoft to host the compilers themselves and we pass through  the requests to them for at https://godbolt.ms and as you can see, it's currently down, so there's not much we can do! :/ We'll have to wait until they can sort it out

**Comment by strega-nil** [comment] 2020-04-22 20:27
We're working on it but our infra people are overworked to hell and additionally have to deal with kids, and so it might take a little longer than it normally would. Please have patience, we'll get it up again asap!

**Comment by PwndDepot** [comment] 2020-05-12 20:53
Is there an update on this? I noticed MSVC x64 is showing but x86 is not.

**Comment by bernd5** [comment] 2020-05-12 20:55
In addition it would be better to have only one "godbolt" for things like "conformance view".

**Comment by partouf** [comment] 2020-05-12 21:06
@bernd5 can you clarify? It should be possible to use the MS compilers in the conformance view on godbolt.org

**Comment by bernd5** [comment] 2020-05-13 08:00
You are right. They seem to be available again on godbolt.org. I thought you would need to use https://www.godbolt.ms directly. But that is fine.

**Comment by PwndDepot** [comment] 2020-05-20 23:36
Now the x64 msvc is showing up at godbolt.ms but neither x64 nor x86 are showing at godbolt.org

**Comment by partouf** [comment] 2020-05-20 23:38
![image](https://user-images.githubusercontent.com/442630/82507879-b9a49680-9b03-11ea-933d-fe4931319acb.png)

I can see them?

**Comment by PwndDepot** [comment] 2020-05-20 23:54
> 
> 
> ![image](https://user-images.githubusercontent.com/442630/82507879-b9a49680-9b03-11ea-933d-fe4931319acb.png)
> 
> I can see them?

Strange, I cleared my cache and now x64 msvc is showing. x86 msvc is still missing or am I missing something?

**Comment by partouf** [comment] 2020-05-20 23:58
x86 has been missing for a while now, it's been reported to MS afaik, but no eta/response as of yet for them to reappear again

**Comment by strega-nil** [comment] 2020-05-21 01:27
Working on it right now 😊

We should be adding extra compilers once we're back too...

**Comment by Dushistov** [comment] 2020-05-30 13:42
> We should be adding extra compilers once we're back too

I hope for 19.26, I see ICE on 19.26 and can not check is it local issue,
or it reproducible on other MSVC installations.

**Comment by bernd5** [comment] 2020-08-09 12:20
Currently it is back - but it responds very often with "bad gateway" or "Not found"

**Comment by apmorton** [comment] 2020-11-03 10:34
godbolt.ms largely seems to be stable lately, so I am going to close this.

If anyone has issues in the future with MSVC compilers please open a new issue.

**Closed by apmorton** 2020-11-03 10:34 UTC
Labels: bug, waiting

**Comment by joaotavora** [comment] 2023-07-03 16:36
> For whoever encounter this problem after Oct. 2021. Click "More" on top left and choose "Reset code and UI layout" might help you reset the dropdown list.

Still relevant in 2023 :-)

**Comment by jeremy-rifkin** [comment] 2023-07-03 18:44
@joaotavora It looks fine on my machine. Godbolt.ms occasionally goes down but it has been more stable recently. Can you try clearing your cache?

**Comment by joaotavora** [comment] 2023-07-03 18:52
I was actually zooming to a colleague's machine when I saw this. What I meant is that the suggested workaround https://github.com/compiler-explorer/compiler-explorer/issues/1929#issuecomment-942860540 fixed it cleanly.

**Comment by jeremy-rifkin** [comment] 2023-07-03 18:53
Oh, gotcha thanks! We can try to dig on our end and see why resetting the layout would have an impact here.
