### ISSUE TITLE
[LIB REQUEST] ROCm libraries/packages for HIP compilation

### ISSUE THREAD

**Issue by Artem-B** [compiler-explorer/compiler-explorer#2805] opened 2021-07-24 08:57 UTC
**Library name:**

ROCm

NOTE: it's not a stand-alone library, but rather a set of libraries, some of them are required for normal HIP compilation.

**Library description:**

ROCm is AMD's software stack for HIP compilation targeting AMD GPUs. It's a rough equivalent of CUDA with its set of libraries, but for AMD GPUs.

**Library repository:**

https://repo.radeon.com/
https://rocmdocs.amd.com/en/latest/Installation_Guide/HIP-Installation.html

**Library homepage:**

https://rocmdocs.amd.com/en/latest/index.html

**Motivation:**

HIP compilation with stand-alone clang, without required support libraries, misses essential features users would expect from a HIP compilation. Things like `__host__` and `__device__` attributes, builtin variables, standard functions and the bitcode libraries that may be required by compiler are unavailable. At the moment clang is executed with `-nocudainc -nocudalib` which forces clang to try compiling the code regardless of ROCm availability, but it severely limits practical use of compiler explorer for HIP.

https://rocmdocs.amd.com/en/latest/Installation_Guide/HIP-Installation.html#hip-installation

The exact set of libraries/packages is TBD. I'll figure out the minimum set and update the issue.

**Comment by RubenRBS** [comment] 2021-07-27 09:19
Hi! Thanks for taking the time to request this library. This would be the first lib for HIP, so it would be great to add it to the site. Unfortunately the installation process seems a bit involved, so it might take as a while to add it to the site :/

**Comment by cgmb** [comment] 2021-09-21 07:18
I would find this quite useful. I've missed Compiler Explorer ever since I moved to HIP from plain C++.

I don't think I'm familiar enough with the Compiler Explorer code base to feel comfortable adding this myself, but I would gladly support anyone that wanted to do the work. I've built the entire ROCm stack from source by hand before.

If you have any trouble at all with the instructions Artem-B has linked, feel free to ping me here on GitHub, in the Compiler Explorer Discord (as Slavik81), or via my amd.com email (which can be found in any of my commits on rocSOLVER).

**Comment by cgmb** [comment] 2021-12-01 04:04
This script builds and installs all libraries needed for HIP programs on ROCm 4.5 to `/opt/compiler-explorer/rocm-4.5.0`:
https://gist.github.com/cgmb/73086a32258934b1eb1f15340304ace6

**Comment by Artem-B** [comment] 2021-12-01 06:55
We do not need to build the packages themselves. We can just get them from the official AMD's repo.
https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation_new.html#installing-rocm-on-linux-distributions

The script, however, is useful as a list of the subset of the packages that may be needed by clang.

**Comment by cgmb** [comment] 2021-12-01 08:29
Oh. I thought the holdup was that the packages needed to go into `/opt/compiler-explorer`. If `/opt/rocm-4.5.0` is fine, then this should be sufficient (also tested in an clean Ubuntu 18.04 docker container, then building and running rocRAND):
https://gist.github.com/cgmb/0966789a647d485d45381cf7ccd0b8a8

**Comment by partouf** [comment] 2021-12-01 08:33
but we can't use apt-get to install these kinds of things, so a middleground somewhere would be nice. Otherwise we do have to use the buildscript

**Comment by Artem-B** [comment] 2021-12-01 09:01
> but we can't use apt-get to install these kinds of things

Can you elaborate on why standard packages are not acceptable? I was assuming that CE uses something standard  (e.g. a Docker container) to build something deployable on AWS.

In any case, there's no magic in those packages. One can just `wget` them from the repo and unpack the files where they belong. It's a bit more work than just apt-get, but still quite a bit less involved, compared to building stuff from scratch.

I'm using ROCm on a Debian machine (AMD does not support it) and I've got it working by installing the packages inside Ubuntu docker and then just copying the files from the container's /opt into the host FS. Something like that may be an option here, too.

**Comment by partouf** [comment] 2021-12-01 09:05
> > but we can't use apt-get to install these kinds of things
> 
> Can you elaborate on why standard packages are not acceptable? I was assuming that CE uses something standard (e.g. a Docker container) to build something deployable on AWS.

If we have to apt-get things for all our instances, we would have to change the base image we use for our instances.

Our usual process is to have something installed on our shared network drive, which would be available for all instances without having to re-image them. But that does require them to be able to run/used standalone from that network drive.

**Comment by Artem-B** [comment] 2021-12-01 09:16
I see. Thank you for the explanation.

In that case, rebuilding may be reasonable. Install-in-container, copy-to-shared-folder approach should also work. I guess the choice would be up to whoever gets to actually do it.

**Comment by cgmb** [comment] 2021-12-01 19:30
> I'm using ROCm on a Debian machine (AMD does not support it)

This is true. Though, I've been volunteering with Debian to help them package ROCm. That's actually where the build script I linked originated from. If you'd like to help, we coordinate on the [debian-ai mailing list](https://lists.debian.org/debian-ai/2021/11/threads.html).

> In any case, there's no magic in those packages. One can just wget them from the repo and unpack the files where they belong.

Well, mostly. HIP can't be installed in a system directory, since clang internally adds the hip include directory to the search path, and that will result in system include directories being reordered (breaking `include_next` in C++ standard library headers).

**Comment by Artem-B** [comment] 2021-12-01 23:12
> HIP can't be installed in a system directory, since clang internally adds the hip include directory to the search path,

clang can handle HIP installed in an arbitrary location. Just point it there with `--cuda-path=...` and it will have the include path order set up the right way. If you run into specific issues with the include order, let me know and we can sort it out.

**Comment by cgmb** [comment] 2021-12-02 02:52
@Artem-B, I've created [a script to reproduce the error](https://gist.github.com/cgmb/c2bf435783d5d77cb779237b8d506e1d) and included the failing build output.

I think [AddHIPIncludeArgs](https://github.com/llvm/llvm-project/blob/27c9e8b45b25614a92539ac6787dbb5670d950b3/clang/lib/Driver/ToolChains/AMDGPU.cpp#L512-L513) is the cause of the problem. The resulting error is essentially the same as in [this FreeBSD bug](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=213217#c2), but due to clang internally adding the isystem flag.

The problem wouldn't affect Compiler Explorer, since it wouldn't be installing in a system path, but I figured it was worth mentioning as a limitation. It's one of many bugs I discovered during this process, and it will take me some time to properly file reports for them all.

**Comment by Artem-B** [comment] 2021-12-02 06:19
Messing with `-isystem` is, in general, not be best idea to start with. Especially when it appears to point to clang's own headers.
My general advice would be just "don't do it". If clang can't find its own headers, there's something wrong with the way it's been installed.

Pointing to HIP includes is also not the right thing to do. I do not think there's a reliable way to insert the path in just the right place. At least I know that's the case for CUDA, but, I believe, HIP is very similar in this regard.

Here's a working example:
```shell
# Pull a docker image with rocm installed (or get it built/installed yourself, does not matter)
$ docker pull ecpe4s/e4s-base-rocm:21.11
# Remove the packages we don't really need for CE.
$ docker run -it ecpe4s/e4s-base-rocm:21.11  bash -c "dpkg --force-all -r rocfft rocblas miopen rocsolver hipblas rocalution rocm-libs  miopen-hip hipfft llvm-amdgpu openmp-extras rocm-clang-ocl rocm-dev rocm-utils ; sleep 99999"
$ docker cp [running container ID]:/opt/rocm-4.3.1 .

# get official LLVM build (i.e. it has no AMD-specific changes)
$ wget https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz
$ tar xf clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz

# Now we have HIP installation and upstream clang in the current directory.
$ echo '#include <math.h>' | ./clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-20.04/bin/clang++ -x hip --rocm-path=$PWD/rocm-4.3.1 -v -c -
```
Observe that clang does find correct HIP installation we've pointed it to and does compile the header.

Specifically, the includes are in correct order without having to specify -isystem paths:

```
clang version 13.0.0 (https://github.com/llvm/llvm-project/ 24c8eaec9467b2aaf70b0db33a4e4dd415139a50)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/art/work/rocm/../clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-20.04/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found CUDA installation: /usr/local/cuda, version 11.2
Found HIP installation: /home/art/work/rocm/rocm-4.3.1, version 4.3.21331-94fc2572
...

#include <...> search starts here:
 /home/art/work/clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-20.04/lib/clang/13.0.0/include/cuda_wrappers
 /home/art/work/rocm/rocm-4.3.1/include
 /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9
 /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/x86_64-linux-gnu/c++/9
 /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/backward
 /home/art/work/clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-20.04/lib/clang/13.0.0/include
 /usr/local/include
 /usr/include/x86_64-linux-gnu
 /usr/include
```

**Comment by cgmb** [comment] 2021-12-02 06:40
> Messing with `-isystem` is, in general, not be best idea to start with. Especially when it appears to point to clang's own headers.

I'm not. [Clang is adding `-internal-isystem /usr/include` itself.](https://github.com/llvm/llvm-project/blob/27c9e8b45b25614a92539ac6787dbb5670d950b3/clang/lib/Driver/ToolChains/AMDGPU.cpp#L512-L513) In your example, you've installed hip to `/home/art/work/rocm/rocm-4.3.1`, which is not a system directory.

**Comment by Artem-B** [comment] 2021-12-02 07:44
> I'm not.  Clang is adding -internal-isystem /usr/include itself. 

I was referring to the paths set in the failing clang invocation in your example script::
> clang -v -std=c++11 -isystem "/usr/lib/clang/13.0.0/include/.." -isystem /usr/hsa/include 

These `-isystem` paths is what broke clang's include arrangement. In general, expected order is (roughly):
- cuda_wrappers
- HIP/CUDA includes
- Standard C++ library
- Clang's own includes
- /usr/include and other regular system headers.

Your example did break that order.

The point of my example was that the only option you should need is `--rocm-path` pointing to the HIP installation.

> In your example, you've installed hip to /home/art/work/rocm/rocm-4.3.1, which is not a system directory.

True, it's not a system directory, but it is a directory that Clang is aware of. Clang does know that the includes in it must be placed just so in the search path so that the whole mix of clang's own headers, system headers, systems C++ library and clang's own C++-related header works.

Installing HIP headers into /usr/include is unlilely to work. clang does rely on the cuda_wrappers/ HIP/CUDA headers to be found *before* any of the system header files, and the rest of clang's headers relies on the system's own includes to be found *after* clang's own headers. You can't satisfy both requirements when HIP and system headers are in the same location.

**Comment by cgmb** [comment] 2021-12-02 09:31
Thanks @Artem-B! That's very informative.

> These -isystem paths is what broke clang's include arrangement.

I was copying what `hipcc` does. I suppose that wouldn't be the first time that `hipcc` has added a weird flag, though the error remains unchanged even if you drop those `-isystem` paths.

> Installing HIP headers into /usr/include is unlilely to work. clang does rely on the cuda_wrappers/ HIP/CUDA headers to be found before any of the system header files, and the rest of clang's headers relies on the system's own includes to be found after clang's own headers. You can't satisfy both requirements when HIP and system headers are in the same location.

[It _seems_ to work](https://gist.github.com/cgmb/3a5053210625196a721e313c63d345b3), though I've only done a few tests. I suppose it would be a bad thing to rely on that anyway if it's not something the compiler or library is expecting.

I learned a lot from this discussion. Thank you very much!

**Comment by Artem-B** [comment] 2021-12-02 16:37
I believe that in older versions of HIP there was an issue with the way they were including the headers in cuda_wrappers that did require that odd ` -isystem "/usr/lib/clang/13.0.0/include/.."` .I think that avoided making clang headers available, but allowed HIP-related headers to `#include <include/cuda_wrappers/something>`.  See https://github.com/ROCm-Developer-Tools/HIP/issues/2082 

I think it's been fixed in rocm-4.2.

@yxsamliu -- do we need anything special other than `--rocm-path` to compile HIP with clang these days?

**Comment by yxsamliu** [comment] 2021-12-03 23:12
No we don't need other options. -isystem "/usr/lib/clang/13.0.0/include/.." is something needed in older ROCm and no longer needed in ROCm 4.5.

I think the reason clang uses -isystem to include HIP header path is to silent some warnings, e.g. the warnings about defining macros with names starting with `__`. I am not sure what is the proper solution. Maybe introduce an option not to include HIP include path?

**Comment by cgmb** [comment] 2022-10-07 05:27
I believe this can be closed once https://github.com/compiler-explorer/compiler-explorer/pull/4097 is merged.

However, I'm not dealing with the nightly compiler builds in that change. If we want to enable HIP for the nightly build of the compiler, do we also need to rebuild HIP each time we update the compiler? The folks I've talked to thus far have indicated that's probably necessary.

What version of HIP should be used in conjunction with the compiler nightly build? Is the answer the same for both amd-stg-open on the AMD fork and main on the upstream LLVM?

**Closed** 2023-07-06 12:39 UTC
Labels: new-libs, request
