### ISSUE TITLE
[REQUEST] `rustc_codegen_gcc` as alternative Rust compiler

### ISSUE THREAD

**Issue by ojeda** [compiler-explorer/compiler-explorer#2683] opened 2021-05-23 21:50 UTC
[`rustc_codegen_gcc`](https://github.com/antoyo/rustc_codegen_gcc) is a `rustc` backend to GCC via `libgccjit`.

While currently it is early days, it can already compile and [run `core`'s tests and pass most of them](https://blog.antoyo.xyz/rustc_codegen_gcc-run-core-tests).

**Comment by dkm** [comment] 2021-05-24 09:15
Would be happy to also work on adding it. Will have a look later to see how to better have it running in CE.
Looks like there are no release, so it has to be build during nightly run from sources.

**Comment by dkm** [comment] 2021-05-25 13:40
@antoyo what would be the easiest way to get a working setup?
IIUC, you first need a patched gcc (f-e using your branch). Do you have any guidelines on how to configure it correctly ?
Then you have some shell scripts to `prepare` and `test`, but I think that's not exactly what is needed here.
I'll try to better understand what is needed, but any hint welcome :)

**Comment by antoyo** [comment] 2021-05-25 23:11
To build libgccjit, just follow [the instructions from its doc](https://gcc.gnu.org/onlinedocs/jit/internals/index.html#working-on-the-jit-library).
Then, you can indeed run `prepare.sh` and `test.sh --release` as it's the simplest way for now to build the gcc backend and the sysroot: make sure the step `[BUILD] sysroot` finishes up properly.
Since I believe you'll want to use `rustc` directly, you won't use `cargo.sh` to use the resulting backend, so you'll need to run rustc like so:
```rust
rustc -Zcodegen-backend=rustc_codegen_gcc/target/release/librustc_codegen_gcc.so
    --sysroot rustc_codegen_gcc/build_sysroot/sysroot/
    -Zno-parallel-llvm
    -C panic=abort
    -C link-arg=-lc
    -o executable
    file_to_compile.rs
```

**Comment by dkm** [comment] 2021-05-26 15:31
Thanks, will try that!

**Comment by dkm** [comment] 2021-06-23 07:37
@antoyo I think I mostly have the build script ok (few tweaks maybe needed still) : https://github.com/dkm/misc-builder/blob/pr/rustc_codegen_gcc/build/build-rustc-cg-gcc.sh
I had strange behavior with rustup locally, but having everything executed from within Docker seems to avoid these.

Currently, the plan is to build everything (gcc/libgccjit, rustc_codegen_gcc) using the above script, find exactly what needs to be packaged and how to install it, and then use already installed rustc compiler (the one used for rust.godbolt.org). 
Does it sound good ? Is there anything to be aware of ? Like rustc version (used to build the backend or to run it) ?

**Comment by antoyo** [comment] 2021-06-23 12:51
It needs to be the rustc version specified in [rust-toolchain](https://github.com/antoyo/rustc_codegen_gcc/blob/master/rust-toolchain).

Thanks for your work!

**Comment by dkm** [comment] 2021-06-23 13:44
Ah, this will be an issue I guess as there's a nightly in CE but it's updated everyday for a fresh one. So, one more detail to solve until it can be added :). Maybe I'll need to package this specific rustc with the cg as a single compiler instead of reusing an already installed one.

**Comment by dkm** [comment] 2021-06-25 20:51
I have updated my build script and it looks correct. I'm wondering if part of it (or most of it?) should not be moved in rustc_codegen_gcc for easier building and then simply rely on it from here ? This script is mostly the result of filtering out test build/exec from your scripts. Also, not sure how stable all these will be in the future. If this is going to change frequently, maybe it ought to be delegated to rustc_codegen_gcc...

I can split/modify this script if you want part of it moved, just tell me :)
I think I have all parts correctly packaged now but I could use a confirmation from you @antoyo  :)

**Comment by antoyo** [comment] 2021-06-30 01:09
I'll do a refactoring of these scripts to make it easier for you.

Also, will you need debug info support? If so, please tell me so that I can prioritize this.

**Comment by dkm** [comment] 2021-06-30 20:11
![Screenshot_2021-06-30 Compiler Explorer](https://user-images.githubusercontent.com/87603/124024473-895e4580-d9ef-11eb-9485-fe067ee4b461.png)


I still need to have rustfilt for demangling. There is currently no mapping between source and assembly because of missing debug info... But this can be added later I think, and CE will pick it up when it lands in the backend during a daily build.

So, I guess, it's good enough for a first introduction. What do you think? Do you want to refactor your script ? Or is my script ok with you?

**Comment by antoyo** [comment] 2021-06-30 20:46
By the way, demangling might not work as I currently replace some characters that are currently unsupported in libgccjit.
Please tell me if you'd like that fixed soon.

I'll try to refactor the scripts tonight.

**Comment by ojeda** [comment] 2021-06-30 21:50
Are you using the `v0` mangling scheme by chance? Perhaps that one works for you because it uses the usual character set (I had a similar issue in a different context and I simply went with `v0`). Since it is the future one, it should not matter much to support the legacy scheme.

**Comment by antoyo** [comment] 2021-06-30 21:59
I am not: I just replace `$` and `.` by `_`, currently.

**Comment by dkm** [comment] 2021-07-02 07:52
Also, is there a way to enable GCC dumps (-f*-dump-*) ? If not, then I can open an issue. I don't even know if libgccjit has something for this

**Comment by antoyo** [comment] 2021-07-02 13:08
@dkm : Yes, that should be possible. Please open an issue with the way you'd like to enable those options (not sure what would be possible here, so maybe just an environment variable?).

**Comment by dkm** [comment] 2021-07-02 13:27
Done : https://github.com/antoyo/rustc_codegen_gcc/issues/44
I think command line option would be the easier here, but that may be only me not knowing CE enough (it's also what I've usually used both for LLVM and GCC ...)

**Comment by antoyo** [comment] 2021-07-03 14:58
@dkm: I refactored the scripts in [this PR][https://github.com/antoyo/rustc_codegen_gcc/pull/46). Please tell me if that would be sufficient for your needs.

**Comment by dkm** [comment] 2021-07-03 19:29
@antoyo I've tested your latest code with the `--emit asm` fix, and it works great.
But now, the objdump is having some problem. After wondering why I could only get a "objdump returned -1" in compiler explorer, I've finally found the issue:
```
22M     /tmp/output
```
and the objdump result is truncated: `\tmov    rbp,rsp\n  33f0c6:\t48 89 7d e8 \n[Truncated]","stderr":"","execTime":"12470"}}` and considered bogus, which is understandable as the text is nearly 140M.

After comparing with regular rustc, it seems the culprit is the sysroot, as using `rustc` with the default LLVM backend also yields a 21M exec, but skipping the `--sysroot .....` makes it all fit in 3M (both LLVM and GCC backends).

Should I open an issue or is it expected ?
Dumb question : is this sysroot needed ? As the results are working without providing it. Or maybe `rustc` will find some sysroot in my system by itself?

**Comment by dkm** [comment] 2021-07-03 19:31
As for the script, I've not looked carefully at your changes yet but we'll do so in the coming days, thanks

**Comment by antoyo** [comment] 2021-07-04 02:32
I'm not sure I understand your issue regarding the sysroot.
What commands do you run?
I guess that if you don't specify the sysroot, you'll use another version not compiled with gcc…

**Comment by dkm** [comment] 2021-07-04 07:24
The issue is that binaries using the sysroot build with gcc backend are very big. Bigger than what compiler explorer is expecting.

The commands used for testing (as computed by compiler explorer): 
```
$ rustc-cg-gcc-master-20210703/bin/rustc -C panic=abort  -C debuginfo=1 -o /tmp/output.rustc.gcc --crate-type bin --color=always /tmp/ex.rs
$ rustc-cg-gcc-master-20210703/bin/rustc -C panic=abort --sysroot /..../rustc-cg-gcc-master-20210703/sysroot -C debuginfo=1 -o /tmp/output.rustc --crate-type bin --color=always /tmp/ex.rs
```
Here's a list of possible fix/workaround that comes to mind, but maybe I'm not thinking of something else? : 
- skip using this sysroot and use the regular one (and I guess in this case I can also skip the part that builds it). Binaries will be a mix of llvm and gcc
- disable "compile to binary" in compiler explorer until size are smaller (and also skip sysroot build in build script)
- have a smaller sysroot (maybe it can be achieved by changing the opt level used ?)
- see if compiler explorer can accept such big binaries (I don't see this as a very good solution, as the text dump is really huge)

**Comment by antoyo** [comment] 2021-07-05 12:35
Why sysroot did you use to reproduce the big binaries with the LLVM backend?

**Comment by partouf** [comment] 2021-07-05 12:49
> The issue is that binaries using the sysroot build with gcc backend are very big. Bigger than what compiler explorer is expecting.
> 
> The commands used for testing (as computed by compiler explorer):
> 
> ```
> $ rustc-cg-gcc-master-20210703/bin/rustc -C panic=abort  -C debuginfo=1 -o /tmp/output.rustc.gcc --crate-type bin --color=always /tmp/ex.rs
> $ rustc-cg-gcc-master-20210703/bin/rustc -C panic=abort --sysroot /..../rustc-cg-gcc-master-20210703/sysroot -C debuginfo=1 -o /tmp/output.rustc --crate-type bin --color=always /tmp/ex.rs
> ```
> 
> Here's a list of possible fix/workaround that comes to mind, but maybe I'm not thinking of something else? :
> 
> * skip using this sysroot and use the regular one (and I guess in this case I can also skip the part that builds it). Binaries will be a mix of llvm and gcc
> * disable "compile to binary" in compiler explorer until size are smaller (and also skip sysroot build in build script)
> * have a smaller sysroot (maybe it can be achieved by changing the opt level used ?)
> * see if compiler explorer can accept such big binaries (I don't see this as a very good solution, as the text dump is really huge)

What's the state of the debugging here, does it indicate file and line numbers?

**Comment by dkm** [comment] 2021-07-05 13:10
> Why sysroot did you use to reproduce the big binaries with the LLVM backend?

The one build by gcc.
- rustc +  '-Z codegen-backend=librustc_codegen_gcc.so' + sysroot = 22M
- rustc + sysroot = 22M
- rustc +  '-Z codegen-backend=librustc_codegen_gcc.so' = 2M
- rustc = 2M
Sorry if that was not clear.

I'll redo all my tests later today. I wanted to provide more numbers in this message but I get new `thread 'rustc' panicked at 'not implemented', src/builder.rs:1527:9` so better clean my workspace and provide something correct.

> What's the state of the debugging here, does it indicate file and line numbers?

Doesn't work yet

**Comment by antoyo** [comment] 2021-07-05 13:12
My preliminary findings show that unused symbols are in the resulting binary, which could be the problem here.
I'm trying to find a solution to this problem.

**Comment by partouf** [comment] 2021-07-05 13:18
> > What's the state of the debugging here, does it indicate file and line numbers?
> 
> Doesn't work yet

Ok, then I can't help you. (there's a better asm-parser in the works that mostly feature-complete on the objdump front)

I would advise disabling binarymode for now.

**Comment by antoyo** [comment] 2021-07-05 13:20
I just found what could be the culprit:
the symbol `__divmodti4@@Base-0x473e07` seems to take ~60M of assembly.
Not sure what this is.

**Comment by dkm** [comment] 2021-07-05 13:26
divmod are functions provided by libgcc, in this case for integer division. 60M looks big for a division :) Is there only one sym, or is it duplicated?

**Comment by antoyo** [comment] 2021-07-05 13:27
As I explained in my edit, it looks like something wrong was happening during my tests: maybe the objdump output was even broken.

**Comment by partouf** [comment] 2021-07-05 13:28
Ah ok. I was thinking __ symbols should be parsed out by this https://github.com/compiler-explorer/compiler-explorer/blob/711ffdb041159265bd184421fb53dda9359fde48/etc/config/c%2B%2B.defaults.properties#L94

**Comment by dkm** [comment] 2021-07-05 13:30
Yes, but the issue is that the truncation may happen before the filtering? The objdump really outputs 150M of text, not sure it gets to the filtering part before being rejected.

**Comment by partouf** [comment] 2021-07-05 13:35
> Yes, but the issue is that the truncation may happen before the filtering? The objdump really outputs 150M of text, not sure it gets to the filtering part before being rejected.

Right, got it. Has always been a problematic feature, but necessary for JS. In the new version, this shouldn't be any problem, but then it still remains; will it actually be readable even when cleaned up...

**Comment by dkm** [comment] 2021-07-05 13:37
If no easy fix can be found to make the sysroot smaller, then we'll disable binary, that is still an acceptable first version, I think...?

**Comment by dkm** [comment] 2021-07-05 19:37
```
dkm@arrakis:~$ RUST_BACKTRACE=1 /..../git/compiler-explorer/rustc-cg-gcc-master-20210703/bin/rustc -C panic=abort -Z codegen-backend=librustc_codegen_gcc.so -C debuginfo=1 -o /tmp/output.s --crate-type bin --color=always /tmp/ex.rs
warning: unused variable: `i`
 --> /tmp/ex.rs:1:9
  |
1 | fn toto(i: i32) {
  |         ^ help: if this is intentional, prefix it with an underscore: `_i`
  |
  = note: `#[warn(unused_variables)]` on by default

thread 'rustc' panicked at 'not implemented', src/builder.rs:1527:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/core/src/panicking.rs:50:5
   3: rustc_codegen_ssa::mir::codegen_mir
   4: rustc_codegen_ssa::base::codegen_instance
   5: <rustc_middle::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define
   6: rustc_codegen_gcc::base::compile_codegen_unit::module_codegen
   7: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
   8: rustc_codegen_gcc::base::compile_codegen_unit
   9: rustc_codegen_ssa::base::codegen_crate
  10: <rustc_codegen_gcc::GccCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  11: rustc_interface::passes::QueryContext::enter
  12: rustc_interface::queries::Queries::ongoing_codegen
  13: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  14: rustc_span::with_source_map
  15: rustc_interface::interface::create_compiler_and_run
  16: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (f586d79d1 2021-06-13) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z codegen-backend=librustc_codegen_gcc.so -C panic=abort -C debuginfo=1 --crate-type bin

query stack during panic:
end of query stack
warning: 1 warning emitted
```
In fact, I can't use gcc backend with regular rustc sysroot. Using regular backend with gcc build sysroot is working (and produces a big binary).

Should I open an issue for the above error, or is it currently expected to be crashing this way?

**Comment by dkm** [comment] 2021-07-05 20:32
A quick look showed that striping removes 12M of debug info + symbols names. Nearly 2.5M are used by `__gccGlobalInit*` functions. Not exactly sure what these are used for, but they all look very similar...

Let me know if I can help somehow. In the meantime, I've prepared changes for having a sysroot-less + binary-disabled compiler.

**Comment by antoyo** [comment] 2021-07-05 21:02
> thread 'rustc' panicked at 'not implemented', src/builder.rs:1527:9

This is weird: are you sure you disabled panics completely (unwinding is not supported yet)?
Yes, please open an issue about it.

> Nearly 2.5M are used by __gccGlobalInit* functions.

Those are a workaround I used to initialize global variables as libgccjit does not have much support for that yet.
I have a feeling that implementing global initializers in libgccjit should help a lot as it might allow even more deadcode to be removed. It's not easy to implement in libgccjit, though.

**Comment by ojeda** [comment] 2021-07-08 18:30
@antoyo Arnd Bergmann and I discussed yesterday how we could start thinking about distributing a GCC toolchain for the kernel with Rust support enabled through `rustc_codegen_gcc` and a few related questions around stability of `libgccjit` etc. I don't see a public email of yours, so if you can contact us via email, that would be great! Thanks a lot!

(Don't worry, we know it is too early, but starting early usually helps -- and congratulations on getting the MCP approved! :)

**Comment by mattgodbolt** [comment] 2021-07-11 22:52
Still open until we merge the CE changes.

**Closed** 2021-07-12 20:35 UTC
Labels: request

**Comment by Serentty** [comment] 2022-06-09 16:22
Would it be possible to get the GCC for other architectures? Right now it can only generate x86 code.
