### ISSUE TITLE
[BUG]: ARM compiler issue on MSVC

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#3457] opened 2022-03-22 17:23 UTC
### Describe the bug

ARM compiler with library gives:

```
Internal Compiler Explorer error: TypeError: Cannot set properties of undefined (setting 'name')
    at Win32VcCompiler.findLibVersion (C:\compiler-explorer\lib\base-compiler.js:461:21)
    at C:\compiler-explorer\lib\base-compiler.js:634:39
    at Proxy.map (C:\compiler-explorer\node_modules\underscore\modules\map.js:13:22)
    at Win32VcCompiler.getIncludeArguments (C:\compiler-explorer\lib\base-compiler.js:633:28)
    at Win32VcCompiler.prepareArguments (C:\compiler-explorer\lib\compilers\win32.js:96:34)
    at Win32VcCompiler.doCompilation (C:\compiler-explorer\lib\base-compiler.js:1245:18)
    at C:\compiler-explorer\lib\base-compiler.js:1650:52
    at async run (C:\compiler-explorer\node_modules\p-queue\dist\index.js:163:29)
Compiler returned: -1
```

### Steps to reproduce

visit the link

### Expected behavior

no internal error...and hopefully some output :)

### Reproduction link

https://godbolt.org/z/GYGxjM7rM

### Screenshots

Not applicable

**Comment by jeremy-rifkin** [comment] 2022-03-31 20:54
I think this is the same as #3412. Issue seems to be caused by using any library + msvc (regardless of arch).

**Comment by partouf** [comment] 2022-04-10 00:50
this should be fixed now

**Closed by partouf** 2022-04-10 00:50 UTC
Labels: bug, MS/Windows
