### ISSUE TITLE
[BUG]: YAMLParseError: Source contains multiple documents

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#5686] opened 2023-10-30 21:04 UTC
### Describe the bug

YAMLParseError: Source contains multiple documents

```
Oct 30 21:00:50 ip-172-30-0-26 compiler-explorer[7111]: YAMLParseError: Source contains multiple documents; please use YAML.parseAllDocuments() at line 3, column 1:
Oct 30 21:00:50 ip-172-30-0-26 compiler-explorer[7111]: Pass:            asm-printe...
Oct 30 21:00:50 ip-172-30-0-26 compiler-explorer[7111]: --- !Analysis
Oct 30 21:00:50 ip-172-30-0-26 compiler-explorer[7111]: ^
Oct 30 21:00:50 ip-172-30-0-26 compiler-explorer[7111]:     at parseDocument (/infra/.deploy/node_modules/yaml/dist/public-api.js:49:29)
Oct 30 21:00:50 ip-172-30-0-26 compiler-explorer[7111]:     at Object.parse (/infra/.deploy/node_modules/yaml/dist/public-api.js:67:17)
Oct 30 21:00:50 ip-172-30-0-26 compiler-explorer[7111]:     at LLVMOptTransformer.processBuffer (file:///infra/.deploy/lib/llvm-opt-transformer.js:71:34)
Oct 30 21:00:50 ip-172-30-0-26 compiler-explorer[7111]:     at LLVMOptTransformer._transform (file:///infra/.deploy/lib/llvm-opt-transformer.js:62:14)
Oct 30 21:00:50 ip-172-30-0-26 compiler-explorer[7111]:     at Transform._write (node:internal/streams/transform:175:8)
Oct 30 21:00:50 ip-172-30-0-26 compiler-explorer[7111]:     at writeOrBuffer (node:internal/streams/writable:399:12)
Oct 30 21:00:50 ip-172-30-0-26 compiler-explorer[7111]:     at _write (node:internal/streams/writable:340:10)
Oct 30 21:00:50 ip-172-30-0-26 compiler-explorer[7111]:     at Writable.write (node:internal/streams/writable:344:10)
Oct 30 21:00:50 ip-172-30-0-26 compiler-explorer[7111]:     at ReadStream.ondata (node:internal/streams/readable:785:22)
Oct 30 21:00:50 ip-172-30-0-26 compiler-explorer[7111]:     at ReadStream.emit (node:events:514:28) {
Oct 30 21:00:50 ip-172-30-0-26 compiler-explorer[7111]:   code: 'MULTIPLE_DOCS',
```

seen in logs shortly before a node shut down

### Steps to reproduce

unsure

### Expected behavior

not this

### Reproduction link

Not applicable

### Screenshots

https://my.papertrailapp.com/systems/ip-172-30-0-26/events?focus=1655753632442503257&selected=1655753632442503257

**Comment by mattgodbolt** [comment] 2023-10-30 21:09
This is actually taking nodes down:
https://my.papertrailapp.com/groups/1243314/events?q=Uncaught+exception%3A+YAMLParseError&selected=1655753013426130944

any YAML error kills the node.

**Comment by OfekShilon** [comment] 2023-10-31 09:59
This actually looks like it originates in some code of mine. I don't have papertrail access - is there a way to reproduce? Perhaps a link or a dump of the input?

**Comment by OfekShilon** [comment] 2023-11-10 20:43
@mattgodbolt  I should probably do as the error suggests and `parseAllDocuments` instead of `parse` with a `FindDocumentEnd` hack:
https://github.com/compiler-explorer/compiler-explorer/blob/286e83530d9a333137093008c17e46f3f690b636/lib/llvm-opt-transformer.ts#L102-L106

I'll just be happier if there would be some repro (or just more info) for the case the current code doesn't handle. Is there anything available?

**Comment by partouf** [comment] 2023-11-11 13:51
We have added some extra logging, but there have not been any issues since. (we only see the last 7 days though)
Matt also added some protection that it doesn't CE, so it will be hard to notice if anything is happening again. I can search for it every week, but it might take a while until we encounter it again.

**Comment by OfekShilon** [comment] 2023-11-18 09:42
@partouf any more occurrences of this?

**Comment by partouf** [comment] 2023-11-19 15:49
Nope

**Comment by partouf** [comment] 2023-12-01 10:55
```
Nov 29 12:01:22 [amazon] error: Error handling opt output: YAMLParseError: Nested mappings are not allowed in compact mappings at line 6, column 15: 
Nov 29 12:01:22 [amazon]   
{
  "code": "BLOCK_AS_IMPLICIT_KEY",
  "linePos": [
    {
      "col": 15,
      "line": 6
    },
    {
      "col": 16,
      "line": 6
    }
  ],
  "name": "YAMLParseError",
  "pos": [
    221,
    222
  ],
  "stack": "YAMLParseError: Nested mappings are not allowed in compact mappings at line 6, column 15:\n\nFunction: olumn: 55 }\n ^\n\n at Composer.onError (/infra/.deploy/node_modules/yaml/dist/compose/composer.js:69:34)\n at Object.resolveBlockMap (/infra/.deploy/node_modules/yaml/dist/compose/resolve-block-map.js:74:21)\n at resolveCollection (/infra/.deploy/node_modules/yaml/dist/compose/compose-collection.js:13:27)\n at Object.composeCollection (/infra/.deploy/node_modules/yaml/dist/compose/compose-collection.js:63:20)\n at Object.composeNode (/infra/.deploy/node_modules/yaml/dist/compose/compose-node.js:31:38)\n at Object.composeDoc (/infra/.deploy/node_modules/yaml/dist/compose/compose-doc.js:33:23)\n at Composer.next (/infra/.deploy/node_modules/yaml/dist/compose/composer.js:149:40)\n at next (<anonymous>)\n at Composer.compose (/infra/.deploy/node_modules/yaml/dist/compose/composer.js:131:25)\n at compose.next (<anonymous>)"
}
```

**Comment by OfekShilon** [comment] 2024-01-06 09:25
Didn't reproduce since. Closing for now.

**Comment by OfekShilon** [comment] 2024-02-26 10:10
Various yaml errors keep popping:
https://compiler-explorer.sentry.io/issues/?alert_rule_id=180927&alert_timestamp=1708401313847&alert_type=email&environment=prod&notification_uuid=be8a74d6-f299-4aec-a9e5-7e3a6649b0d4&project=102028&query=url%3A%22https%3A%2F%2Fgodbolt.org%2Fapi%2Fcompiler%2Fcclang_trunk%2Fcompile%22&referrer=event-tags

One of these is similar to this bug, and all look like true bad yaml generation (maybe work-in-progress on clang trunk?)

**Comment by OfekShilon** [comment] 2024-12-01 21:05
Pretty sure we finally got this right in https://github.com/compiler-explorer/compiler-explorer/pull/6749, didn't see these errors pop since.

**Closed by OfekShilon** 2024-12-01 21:05 UTC
Labels: bug, high priority
