### ISSUE TITLE
[BUG]: Fortran example function fails to compile with flang-trunk

### ISSUE THREAD

**Issue by JPeroutek** [compiler-explorer/compiler-explorer#3704] opened 2022-05-23 17:09 UTC
### Describe the bug

The default `square` function example fails to compile with the `flang-trunk` compiler.  

```
Output of flang-trunk (experimental) (Compiler #1)

/opt/compiler-explorer/clang-llvmflang-trunk/bin/flang: line 431: gfortran: command not found
flang: in /app, gfortran failed with exit status 127: gfortran -g -S -fparse-only -g -o /app/output.s -S -fparse-only /app/example.f90
Compiler returned: 127
```

### Steps to reproduce

1. go to webpage
2. change language to fortran
3. change compiler to `flang-trunk`
4. examind output

### Expected behavior

The assembly output should appear, and compilation should not fail.

### Reproduction link

https://godbolt.org/z/758T3hx18

### Screenshots

Not applicable

### Operating System

Windows 10

### Browser version

Firefox 100.0 64 bit

**Comment by partouf** [comment] 2022-05-23 17:22
Thanks, we're already aware of this. Duplicate of #3476

**Closed by partouf** 2022-05-23 17:22 UTC
Labels: bug
