### ISSUE TITLE
[BUG]: Compiler explorer show me a black blank screen when I open a saved program link

### ISSUE THREAD

**Issue by honey-speaks-tech** [compiler-explorer/compiler-explorer#4621] opened 2023-01-19 16:48 UTC
### Describe the bug

Hi,
Compiler Explorer is really a boon for programmers like us.

Here is a bug which I noticed when I open a saved program link.
![image](https://user-images.githubusercontent.com/2928745/213503841-f8fb3961-53d4-43fa-af6c-b8d4596cf96f.png)

### Steps to reproduce

1. Open one tab in your web browser (I used Google Chrome) with compiler explorer (link with a program preloaded)
2. In another tab, open another preloaded link (I tried to open my link - https://godbolt.org/z/h5TvsKbj4)
3. Second one shows a black blank screen.
4. I tried opening the second link in another browser (I used Microsoft Edge). Worked like a charm!
![image](https://user-images.githubusercontent.com/2928745/213504859-e4145b65-b41b-4b3f-a6ae-28982cdb4037.png)

### Expected behavior

Both tabs should show the saved programs in the link

### Reproduction link

Not applicable

### Screenshots

![image](https://user-images.githubusercontent.com/2928745/213504993-64985a5a-0878-478a-9973-b493d4083d66.png)

**Comment by jeremy-rifkin** [comment] 2023-01-19 17:05
The link works for me in firefox and chrome. Does clearing the cache in the original browser fix it? Are there any errors in the console for the original browser?

**Comment by RubenRBS** [comment] 2023-01-20 21:34
I can confirm that the link also works for me, weird

**Comment by honey-speaks-tech** [comment] 2023-01-24 13:10
My chrome version is Version 109.0.5414.75 (Official Build) (64-bit)

I retested it today, now it's working. Even though for a some time, when I opened the second tab, the same black screen appeared. The black screen appeared for 3 to 5 seconds. But eventually, it displayed the program.

That day, but I was facing the same issue all the time. Probably, cache. I am not sure.

**Comment by jeremy-rifkin** [comment] 2023-01-24 21:20
Thank you @honey-speaks-tech, I'm glad it's now working. Let's attribute this to someone feeding the Gremlins after midnight. I will close the issue but please let us know if you encounter the issue again!

**Closed by jeremy-rifkin** 2023-01-24 21:20 UTC
Labels: bug
