### ISSUE TITLE
Bugged asm parsing or filtering when compiling to binary

### ISSUE THREAD

**Issue by jeremy-rifkin** [compiler-explorer/compiler-explorer#3804] opened 2022-06-22 23:37 UTC
There seems to be a little bug with the parsing or filtering when compiling to binary here https://godbolt.org/z/zM1brnvvr, the label for the max function is `[space]max(int*, unsigned long)>:` instead of `max(int*, unsigned long):`

**Comment by partouf** [comment] 2022-06-22 23:55
I'm a little confused. Can you explain it more detailed for me?

**Comment by jeremy-rifkin** [comment] 2022-06-22 23:59
I will try: Perhaps better explained in the opposite order:
- `max` doesn't show up when compiling to binary here <https://godbolt.org/z/n7x4Mesr5>, even with all filters off
- `max` does show up when another function (`foo`) is included before it <https://godbolt.org/z/eWo8v355G>
  - The label for `max` is strangely formatted which I would guess is related to why it doesn't show up without another function before it

**Comment by partouf** [comment] 2022-06-25 13:46
Well this is weird... I can't reproduce locally

**Comment by partouf** [comment] 2022-06-25 14:02
But I can repro on the production instances.. so they must have a different asm-parser version than I have

**Comment by partouf** [comment] 2022-06-25 14:21
Fixed by updating to the latest version, it was still using an old version from January

**Comment by jeremy-rifkin** [comment] 2022-06-25 14:22
Thanks @partouf!

**Closed by partouf** 2022-06-25 14:21 UTC
