### ISSUE TITLE
[BUG]: _mm_bsrli_si128 disappears from binary output

### ISSUE THREAD

**Issue by Alcaro** [compiler-explorer/compiler-explorer#6188] opened 2024-02-25 13:13 UTC
### Describe the bug

title

### Steps to reproduce

```c
#include <immintrin.h>

__m128i a(__m128i b)
{
    return _mm_bsrli_si128(b, 4);
}
```
-O2 and compile to binary object

### Expected behavior

```
a(long long __vector(2)):
66 0f 73 d8 04
        psrldq  xmm0, 4
c3
        ret
```
Actual behavior:
```
long __vector(2))::
c3
 ret
```
Or if c++ demangling is disabled, the entire function just disappears.

### Reproduction link

https://godbolt.org/z/bc3rqvhh9

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment] 2024-02-25 23:09
Interestingly I can't reproduce locally, without using `asm-parser` - will file there.

**Comment by OfekShilon** [comment] 2024-11-15 20:24
Seems fixed, closing.

**Closed by OfekShilon** 2024-11-15 20:24 UTC
Labels: bug
