### ISSUE TITLE
[LIB REQUEST] INSERT LIB NAME HERE

### ISSUE THREAD

**Issue by shashvatsawar** [compiler-explorer/compiler-explorer#4145] opened 2022-10-11 16:49 UTC
Numpy for python

**Comment by shashvatsawar** [comment] 2022-10-14 08:59
It's not working for me,
giving "ModuleNotFoundError: No module named 'numpy'" error.
is python interpretar a different thing? I selected python from list of compilers.

**Comment by partouf** [comment] 2022-10-14 09:15
> I believe its already in there,
> 
> ```python
> import numpy
> numpy.array([1,2,3])
> ```
> 
> this works on the website selecting python as interpreter.

I think it only works because it doesn't check if it actually exists. You can replace numpy by any other valid identifier and it will still "work" if you keep execution off.

https://godbolt.org/z/eK5j5T3vj

But obviously that doesn't actually exist.

**Comment by RubenRBS** [comment] 2022-10-14 15:05
Closing as duplicate of #3201

**Closed by RubenRBS** 2022-10-14 15:05 UTC
Labels: new-libs, request, duplicate, lang-python
