### ISSUE TITLE
llvm-mca vhaddps has latency 100 for znver1 architecture

### ISSUE THREAD

**Issue by marcovtje** [compiler-explorer/compiler-explorer#3263] opened 2022-01-16 21:56 UTC
Put this through llvm-mca 

vhaddps xmm4,xmm3,xmm3                   // x  im1*re2+re1*im2

with -mcpu=znver1 and the result is strangely enough (note the "100" in the [2] column, Agner Fog says 7 or 8). Note also that this is all 128-bit registers.

Instruction Info:
[1]: #uOps
[2]: Latency
[3]: RThroughput
[4]: MayLoad
[5]: MayStore
[6]: HasSideEffects (U)

[1]    [2]    [3]    [4]    [5]    [6]    Instructions:
 1      100   0.25                        vhaddps       xmm4, xmm3, xmm3
 1      1     0.50           *            movq  qword ptr [r8], xmm4

**Comment by dkm** [comment] 2022-01-16 23:03
Hi !
Are you reporting a bug in compiler explorer or in the llvm-mca tool ? I guess it should be reported in https://github.com/llvm/llvm-project/issues?q=is%3Aissue+is%3Aopen+llvm-mca instead :)

**Comment by marcovtje** [comment] 2022-01-17 10:54
dkm: I now did. I don't have -mca myself due windows work computer, which is why I use godbolt. I mentioned it is "trunk" (as I see on Godbolt), is that really the last dev version?

Would you mind keep it open a while longer in case they have questions in the coming days? Thanks

**Comment by dkm** [comment] 2022-01-17 19:25
Of course, no worries :). Also, for this kind of report, you may want to "share" a specific example by clicking the "share" in the top right corner

**Comment by dkm** [comment] 2022-01-30 17:54
@marcovtje I see the issue is opened and active in llvm. I think we can close this one as there's nothing we can do on our side at the moment (closed issue still accepts comments and can be reopened!)

**Closed by dkm** 2022-01-30 17:54 UTC

**Comment by marcovtje** [comment] 2022-01-30 20:26
Yes. fine, thank you all!
