### ISSUE TITLE
Irvine32.inc

### ISSUE THREAD

**Issue by bharat-dussa** [compiler-explorer/compiler-explorer#2256] opened 2020-10-04 15:32 UTC
This library is not issued in your LIbraries section

**Comment by partouf** [comment] 2020-10-04 15:34
Dupe of https://github.com/compiler-explorer/compiler-explorer/issues/1235

If you can provide any more information about this library, please do.

**Comment by bharat-dussa** [comment] 2020-10-05 15:45
> Dupe of https://github.com/compiler-explorer/compiler-explorer/issues/1235
> 
> If you can provide any more information about this library, please do.


It is used to simplify task related to input and output
And string handling.

I am providing the link which i found already a repo may be available for this library.

[https://stackoverflow.com/questions/54386649/what-is-the-irvine32-library-and-why-do-we-use-it]()

**Comment by partouf** [comment] 2020-10-05 16:37
Ok, so this is a Windows ASM library, specifically for MASM? I guess maybe we could make it get it to work through the Wine MSVC installations, but it would be a longshot.

**Comment by apmorton** [comment] 2020-11-03 12:57
closing as dup of #1235

**Closed by apmorton** 2020-11-03 12:57 UTC
