### ISSUE TITLE
[BUG]: Save/Load button can activate when releasing a selection

### ISSUE THREAD

**Issue by lolbinarycat** [compiler-explorer/compiler-explorer#6691] opened 2024-07-05 18:47 UTC
### Describe the bug

the "Load and save editor text" window appears when it shouldn't.

### Steps to reproduce

1. go to godbolt.org
2. choose any compiler (i found it when using Rust, but i doubt it matters)
3. position your mouse pointer anywhere within the source code editing area
4. click and drag (selecting text if there is any), moving your pointer so the "Save/Load" button is highlighted.
5. release all mouse buttons

### Expected behavior

the state of the UI should not change, since buttons should only activate their `onclick` handler when the `mousedown` and `mouseup` events happen over the same element, per [the mdn web docs](https://developer.mozilla.org/en-US/docs/Web/Events)

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

NixOS 23.11.7071.71bae31b7dbc (Tapir) x86_64

### Browser version

Mozilla Firefox 125.0.3

**Comment by jeremy-rifkin** [comment] 2024-07-05 18:51
Looks like the same behavior noted in #5824

**Comment by OfekShilon** [comment] 2024-08-11 14:58
Duplicate of #5824

**Closed by OfekShilon** 2024-08-11 14:58 UTC
Labels: bug
