### ISSUE TITLE
[BUG] gtest libraries not linked

### ISSUE THREAD

**Issue by rafaelreyesalvarez** [compiler-explorer/compiler-explorer#2074] opened 2020-07-13 02:13 UTC
It appears that the Google Test libraries are not being added to the compiler arguments, causing the linker to fail to resolve some necessary symbols. 

```
#include <gtest/gtest.h>

TEST(link, please)
{
}
```

In [this snippet](https://godbolt.org/z/rKrars), the compiler (or more specifically the linker) complains about the `main` function being undefined, although typically this function is defined in the `gtest_main` library that comes with Google Test.

I believe the Google Test libraries that should be added are `gtest`, `gtest_main`, `gmock` and `gmock_main`. 

Note that the Google Test _headers_ are found correctly, since the include path is passed to the compiler arguments. The missing part is the actual library binaries (`.a` or `.so` files).

**Comment by partouf** [comment] 2020-07-13 02:43
This mainly happens because we currently don't support library binaries and linking to them.

*cough* don't tell anyone, but try it on beta https://godbolt.org/beta/z/9c6jbY *cough*

**Comment by rafaelreyesalvarez** [comment] 2020-07-13 03:13
Oh, I see. Using the beta then. Thanks!

**Comment by mattgodbolt** [comment] 2020-07-13 12:47
The beta site might go down at any point, but...we hope to have this ready for prime time soon :)  Closing as a duplicate of #1932

**Closed by mattgodbolt** 2020-07-13 12:47 UTC
Labels: bug
