### ISSUE TITLE
[BUG]: Simple GPU kernel fails to compile with "internal error"

### ISSUE THREAD

**Issue by eyalroz** [compiler-explorer/compiler-explorer#3413] opened 2022-02-28 20:57 UTC
### Describe the bug

Weird compiler internal error with NVCC 11.5 on GodBolt:
```
Internal Compiler Explorer error: TypeError: Cannot read properties of undefined (reading 'split')
    at SassAsmParser.processBinaryAsm (/infra/.deploy/lib/parsers/asm-parser.js:620:54)
    at SassAsmParser.processAsm (/infra/.deploy/lib/parsers/asm-parser.js:265:41)
    at SassAsmParser.process (/infra/.deploy/lib/parsers/asm-parser.js:657:21)
    at NvccCompiler.processAsm (/infra/.deploy/lib/base-compiler.js:1840:25)
    at NvccCompiler.afterCompilation (/infra/.deploy/lib/base-compiler.js:1801:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /infra/.deploy/lib/base-compiler.js:1775:20
    at async run (/infra/.deploy/node_modules/p-queue/dist/index.js:163:29)
Compiler returned: -1
```

### Steps to reproduce

Try to compile:
```
__global__ void p10(double* result, int n)
{ 
    *result = pow(10, n);
}
```
with NVCC 11.5.0 on Godbolt 

### Expected behavior

There should be no error. With NVCC V11.5.119, on my machine, this compiles fine.

### Reproduction link

https://godbolt.org/z/Pr1v1Tbq9

### Screenshots

Not applicable

### Operating System

Devuan GNU/Linux Chimaera

### Browser version

Firefox 97

**Comment by partouf** [comment] 2022-02-28 21:07
duplicate of https://github.com/compiler-explorer/compiler-explorer/issues/3276 - but thanks for the example

**Closed by partouf** 2022-02-28 21:07 UTC
Labels: bug
