### ISSUE TITLE
Indented preprocessing directives are not show in blue color in the editor

### ISSUE THREAD

**Issue by VladimirReshetnikov** [compiler-explorer/compiler-explorer#879] opened 2018-03-22 19:21 UTC
```
#if defined(__has_include)
    #if __has_include(<io.h>)
        #include <io.h>
    #endif 
#endif 
```

![image](https://user-images.githubusercontent.com/1231606/37793289-718d78b4-2dcb-11e8-99d2-cdb1ddfbfcae.png)

https://godbolt.org/z/qjYaKv

**Comment by mattgodbolt** [comment] 2018-04-02 12:55
Seems to be fixed by https://github.com/Microsoft/monaco-editor/issues/687 - hopefully will get this when we get the latest Monaco.

**Comment by mattgodbolt** [comment] 2018-10-01 02:52
Paging #890  (@jaredwy I know you're snowed under; any luck with that?)

**Comment by mattgodbolt** [comment] 2019-10-29 13:35
Latest monaco does not fix this: we'll have to patch cpp lang (which we do for a number of other reasons anyway).

**Comment by mattgodbolt** [comment] 2021-02-15 23:44
Will be able to undo the local change if https://github.com/microsoft/monaco-languages/pull/125 lands

**Comment by mattgodbolt** [comment] 2021-02-15 23:47
@RubenRBS if you feel like hacking, we now have a fork of monaco-languages in the compiler explorer project you can hack on (in a branch) and then PR to the main monaco.

**Comment by mattgodbolt** [comment] 2021-03-28 21:10
Sadly not fixed in monaco 0.23.0

**Comment by partouf** [comment] 2021-03-28 21:14
I wonder, do our changes in `cppp-mode` not cause this somehow?

**Comment by mattgodbolt** [comment] 2021-03-28 21:15
I don't think so. I've backed out most of those now I've updated monaco. we only delete a few keywords and add a couple more. I'm looking at the monaco-languages project to double check now.

**Comment by mattgodbolt** [comment] 2021-03-28 21:22
Confirmed, I can repro in the monaco-languages tests

**Comment by mattgodbolt** [comment] 2021-03-28 21:46
Fix upstreamed; feasibly we can patch in cppp, just prepending:

```
			[/^\s*#\s*include/, { token: 'keyword.directive.include', next: '@include' }],
			[/^\s*#\s*\w+/, 'keyword.directive'],
```

to the `root` should do it.

**Comment by mattgodbolt** [comment] 2021-03-28 22:17
Going to close (though if/once monaco merges my PR we can undo my hack)

**Closed by mattgodbolt** 2021-03-28 22:17 UTC
Labels: bug, ui, waiting
