### ISSUE TITLE
[BUG] conformance viewer shows wrong (random?) pass/fail information on page load

### ISSUE THREAD

**Issue by zygoloid** [compiler-explorer/compiler-explorer#2490] opened 2021-03-12 01:48 UTC
**Describe the bug**
Loading a page with a conformance viewer for invalid appears to show random pass/fail results for the compilers in the conformance viewer.

**To Reproduce**
* Open a conformance viewer, add some compilers.
* Enter some invalid code. Note all the compilers show a cross icon.
* Reload the page. Note that some of the compilers now show a tick icon.

**Expected behavior**
The conformance viewer on page load correctly displays compile success / fail for each compiler.

**Link**
https://godbolt.org/z/3T9dY4 (try reloading a few times to see the pass/fail status seemingly randomly change)

**Additional context**
My guess is that this is a race condition: some of the compilers are running before the editor's contents are populated, so they report that it's valid, and they don't get rerun when the editor's contents get filled in moments later.

**Comment by partouf** [comment] 2021-03-12 02:11
Interesting. Obviously this shouldn't compile for any compiler... But it somehow appears it does.. until click on compiler output.

**Comment by RubenRBS** [comment] 2021-03-19 17:29
Hi! Thanks for taking the time to report the bug. This was a weird one.
It _might_ be fixed now that I removed a line that past me would have had a good reason to add, but as I can't reproduce it any longer locally and everything seems to still work, I'll close this as soon as the fix lands in the site and we can confirm that it has indeed been fixed :)

**Comment by partouf** [comment] 2021-03-20 19:00
@RubenRBS 's fix is live. And I think it has worked. Thanks!

**Comment by mattgodbolt** [comment] 2021-08-05 15:39
Looks like something similar is happening again: Reported on CppLang slack by Nir Friedman.

This link: https://godbolt.org/z/d4s15jo99

> before, I clicked this link, and deleted the word "protected" and none of the compilers changed from red to green

**Comment by RubenRBS** [comment] 2021-08-06 04:04
Ooops, sorry. I'll see if I can properly fix it this time

**Comment by OfekShilon** [comment] 2024-12-01 19:40
Time heals all wounds, and this one was no exception. Closing as fixed.

**Closed by OfekShilon** 2024-12-01 19:40 UTC
Labels: bug, ui
