### ISSUE TITLE
[REQUEST] Add diff view for 2 Compiler Explorer URLs

### ISSUE THREAD

**Issue by kunaltyagi** [compiler-explorer/compiler-explorer#1968] opened 2020-05-14 18:02 UTC
**Is your feature request related to a problem? Please describe.**
Godbolt is used to share code, and many time, it is difficult to see what was changed by someone from link1 to link2

**Describe the solution you'd like**
A way to diff sources/output at 2 different URL. This might be difficult/weird, so instead we can have
* import source in new source editor by URL
* Allow diff tool to diff between 2 source editors as well

**Describe alternatives you've considered**
* Copy-paste the source and diff manually  <-- Please no 😄
* Source control integration (eg: git repo from GitHub/GitLab): import + export repository similar to [repl.it](https://repl.it/languages/cpp)  <-- Most promising, but most difficult
* Source control for all snippets <-- Like prev, but server side and possibly hidden from users

**Comment by partouf** [comment] 2020-05-15 13:46
I know this isn't a great solution to this, and we probably need to think of something proper - but if you load the examples one after another, you can diff them using the local history option under More -> History

**Comment by kunaltyagi** [comment] 2020-05-15 14:01
Nice. Didn't know that. But the GUI is messed up for me
<img width="184" alt="Screen Shot 2020-05-15 at 22 59 09" src="https://user-images.githubusercontent.com/2657068/82058644-fb969c80-96ff-11ea-8466-0e241e164799.png">

**Comment by partouf** [comment] 2020-05-15 14:03
What browser/os are you using?

**Comment by kunaltyagi** [comment] 2020-05-15 14:23
Firefox 76/MacOS 10.15.4

**Comment by OfekShilon** [comment] 2024-12-01 20:04
Can't reproduce, closing for now.
@kunaltyagi  please re-open if the history view is still mangled for you.

**Closed by OfekShilon** 2024-12-01 20:04 UTC
Labels: bug, enhancement, ui, request
