### ISSUE TITLE
[BUG]: F# compiler not working at all

### ISSUE THREAD

**Issue by OkkeHendriks** [compiler-explorer/compiler-explorer#4675] opened 2023-02-01 11:18 UTC
### Describe the bug

Compile error at most basic example for F#:

`/opt/compiler-explorer/dotnet-v7.0.0/.dotnet/sdk/7.0.100-rc.1.22431.11/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1064: Package FSharp.Core, version 6.0.6-beta.22422.11 was not found. It might have been deleted since NuGet restore. Otherwise, NuGet restore might have only partially completed, which might have been due to maximum path length restrictions. [/app/CompilerExplorer.fsproj]
Compiler returned: 1`

### Steps to reproduce

1. Visit this example https://godbolt.org/z/bnfqrbKsh
2. Compile
3. Look at compile output

### Expected behavior

No compile error.

### Reproduction link

https://godbolt.org/z/bnfqrbKsh

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment] 2023-02-01 14:14
Thanks: probably related to #4609 - we'll investigate.

**Comment by partouf** [comment] 2023-02-17 17:50
To me this looks like the needed packages have been incorrectly built alongside of the compiler.

We used to provide `fsharp.core` separately from a pre-populated folder I had .net download from a non-jailed instances of CE and placed into `/opt/compiler-explorer/dotnet_nuget-v6.0.0/packages`. There's currently no equivalent for any of the versions.

I guess we can do the same trick again and run the compiler without a jail locally and upload the nuget packages to the website.

**Comment by hez2010** [comment] 2023-04-22 15:31
It is pretty weird because the package of fsharp.core nuget package is already shipped with the sdk. There shouldn't be any additional nuget package needed.
I can also successfully build F# project in a completely brand-new environment without Internet access, but not sure why it doesn't work with CE.

**Comment by partouf** [comment] 2023-04-22 15:56
Once you did, its cached and you wont need internet anymore, thats true

**Comment by diego-crespo** [comment] 2023-12-29 02:10
Hi. I'm also running into this issue. None of the versions I've tried work for me I see that #4609 was merged but it doesn't seem to have resolved the issue

**Comment by partouf** [comment] 2023-12-29 14:47
The issue was not related to 4609, it was because of changes to the build process of the compilers and reinstalling new versions that did not take into account F#

**Comment by partouf** [comment] 2024-02-11 00:04
I'm a little confused as to why this is resolved, but we did fix a bug in the paths that the compiler was using..

If anyone can reproduce the original problem, please let us know, but for now I'm closing this issue

**Closed by partouf** 2024-02-11 00:04 UTC
Labels: bug
