### ISSUE TITLE
[BUG]: MSVC gives "Internal Compiler Explorer error ... property 'localeCompare' of undefined" on some code snippets

### ISSUE THREAD

**Issue by HolyBlackCat** [compiler-explorer/compiler-explorer#3125] opened 2021-11-20 14:16 UTC
### Describe the bug

Trying to compile some specific C++ snippets with MSVC gives me following error:
```
Internal Compiler Explorer error: TypeError: Cannot read property 'localeCompare' of undefined
    at C:\compiler-explorer\lib\asm-parser-vc.js:296:36
    at Array.sort (<anonymous>)
    at AsmParser.resultObjectIntoArray (C:\compiler-explorer\lib\asm-parser-vc.js:273:23)
    at AsmParser.processAsm (C:\compiler-explorer\lib\asm-parser-vc.js:269:21)
    at AsmParser.process (C:\compiler-explorer\lib\asm-parser.js:568:21)
    at Win32VcCompiler.processAsm (C:\compiler-explorer\lib\base-compiler.js:808:25)
    at C:\compiler-explorer\lib\base-compiler.js:777:34
    at async run (C:\compiler-explorer\node_modules\p-queue\dist\index.js:255:29)
Compiler returned: -1
```

### Steps to reproduce

1. Go to https://gcc.godbolt.org
2. Select `x64 msvc v19.latest` as C++ compiler
3. Paste following code:
```c++
#include <string>

struct Outer {
  struct {
    std::string name;
  } inner;
};

Outer outer;
```
4. Look at the output window to see the above error. The assembly window is stuck at `<Compiling...>`.

### Expected behavior

No internal errors. Either the assembly output or a compiler error.

### Reproduction link

https://gcc.godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:13,endLineNumber:9,positionColumn:13,positionLineNumber:9,selectionStartColumn:13,selectionStartLineNumber:9,startColumn:13,startLineNumber:9),source:'%23include+%3Cstring%3E%0A%0Astruct+Outer+%7B%0A++struct+%7B%0A++++std::string+name%3B%0A++%7D+inner%3B%0A%7D%3B%0A%0AOuter+outer%3B'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:49.92167101827676,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:vcpp_v19_latest_x64,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'1',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1,tree:'1'),l:'5',n:'0',o:'x64+msvc+v19.latest+(C%2B%2B,+Editor+%231,+Compiler+%231)',t:'0')),k:50,l:'4',m:50,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compiler:1,editor:1,fontScale:14,fontUsePx:'0',wrap:'1'),l:'5',n:'0',o:'Output+of+x64+msvc+v19.latest+(Compiler+%231)',t:'0')),header:(),l:'4',m:50,n:'0',o:'',s:0,t:'0')),k:50.07832898172324,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4

### Screenshots

Not applicable

### Operating System

Ubuntu 20.04.3

### Browser version

FF 94.0 x64

**Comment by partouf** [comment] 2021-11-20 21:17
duplicate of https://github.com/compiler-explorer/compiler-explorer/issues/2386

**Closed by partouf** 2021-11-20 21:17 UTC
Labels: bug
