### ISSUE TITLE
[LIB REQUEST] Numpy in Python

### ISSUE THREAD

**Issue by abid-k** [compiler-explorer/compiler-explorer#3671] opened 2022-05-16 05:08 UTC

**Comment by RubenRBS** [comment] 2022-05-16 08:31
Hi! Unfortunately, Python library support is not something that we can easily tackle, so unless there is a major breakthru, it's unlikely that we'll support it in the near future, sorry :/

Closing as a duplicate of #3201

**Closed by RubenRBS** 2022-05-16 08:31 UTC
Labels: duplicate
