### ISSUE TITLE
[BUG]: Unable to load most recently saved file from disk after restoring browser session

### ISSUE THREAD

**Issue by joeri-hu** [compiler-explorer/compiler-explorer#4428] opened 2022-12-13 01:12 UTC
### Describe the bug

When I have 2 sessions (tabs) open in CE and I crash my browser, it will load the contents of the tab which I've touched last in both CE tabs (after restoring the browser session). If I happen to have saved the contents of the first CE tab before the browser crash and I try to load it in either tab (since both CE tabs have loaded the content from the 2nd CE tab from cache), nothing seems to happen, the file is not being loaded from disk. If I try to load a completely different source file, it works though. It seems as if CE thinks the contents from the 1st CE tab was reloaded from cache and because it is the same as the file I'm trying to load from disk, it doesn't actually loads it.

### Steps to reproduce

See bug description.

### Expected behavior

The file should be loaded from disk.

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

Windows 11 Version 21H2 (OS Build 22000.1281)

### Browser version

Chrome 108.0.5359.99 (64-bit)

**Comment by jeremy-rifkin** [comment] 2023-06-17 19:57
I'm not able to reproduce but this might have been fixed by #5111. Please feel free to re-open though if you find the issue is persisting!

**Closed by jeremy-rifkin** 2023-06-17 19:57 UTC
Labels: bug
