### ISSUE TITLE
[BUG] Internal Compiler Explorer error with msvc

### ISSUE THREAD

**Issue by chausner** [compiler-explorer/compiler-explorer#2386] opened 2021-01-13 00:17 UTC
**Describe the bug**
```
#2 with x64 msvc v19.28
Internal Compiler Explorer error: TypeError: Cannot read property 'localeCompare' of undefined
    at C:\compiler-explorer\lib\asm-parser-vc.js:296:36
    at Array.sort (<anonymous>)
    at AsmParser.resultObjectIntoArray (C:\compiler-explorer\lib\asm-parser-vc.js:273:23)
    at AsmParser.processAsm (C:\compiler-explorer\lib\asm-parser-vc.js:269:21)
    at AsmParser.process (C:\compiler-explorer\lib\asm-parser.js:568:21)
    at Win32VcCompiler.processAsm (C:\compiler-explorer\lib\base-compiler.js:808:25)
    at C:\compiler-explorer\lib\base-compiler.js:777:34
    at async run (C:\compiler-explorer\node_modules\p-queue\dist\index.js:255:29)
Compiler returned: -1
```

**To Reproduce**
Compile with x64 msvc v19.28, /O2 /std:c++17
```c++
// CPP program to illustrate  
// concept of Anonymous Class 
#include <iostream> 
using namespace std; 
  
// Anonymous Class : Class is not having any name 
class
{ 
    // data member 
    int i;  
public: 
    void setData(int i) 
    { 
        // this pointer is used to differentiate 
        // between data member and formal argument. 
        this->i = i; 
    } 
    void print() 
    { 
        cout << "Value for i : " << this->i << endl; 
    } 
      
} obj1;     // object for anonymous class 
  
// Driver function 
int main() 
{ 
    obj1.setData(10); 
    obj1.print(); 
    return 0; 
} 
```

**Link**
https://godbolt.org/z/zTzW3z

**Comment by mattgodbolt** [comment] 2021-01-13 16:16
Thanks for filing this!

**Comment by partouf** [comment] 2021-02-24 00:57
Ok. This is actually a duplicate of #2093 and was fixed here https://github.com/compiler-explorer/compiler-explorer/commit/75ba44c8fd0478882a282fc2d289959aef960837#diff-b92aa597dadf09dbd3514958aaf0c2b7754622cec50996b169be4a90cb14654c

I will try and see how we can get a more recent commit live

**Comment by partouf** [comment] 2022-06-03 19:55
this has been fixed for a while

**Closed by partouf** 2022-06-03 19:55 UTC
Labels: bug
