### ISSUE TITLE
[BUG]: MSVC stopped work with multi-file cmake feature?  Keeps talking about "example.cpp" 

### ISSUE THREAD

**Issue by Cazadorro** [compiler-explorer/compiler-explorer#4583] opened 2023-01-12 20:57 UTC
### Describe the bug

Yesterday I tried to use MSVC  with this feature, it worked (though godbolt seemed to incorrectly not pass c++20 arguments on to MSVC).  Today it doesn't work (normal ones that can compile to binary), can't get any version x86 MSVC or x64 MSVC to work 

### Steps to reproduce

Visit the example godbolt project to test the multi-file feature https://godbolt.org/z/WseTsM8YG

Replace compiler with x64 msvc v19.latest

Try to compile, get following result: 

```
example.cpp
<source>(1): error C2065: 'shapes': undeclared identifier
<source>(1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
<source>(3): error C2146: syntax error: missing ';' before identifier 'cmake_minimum_required'
ASM generation compiler returned: 2
example.cpp
<source>(1): error C2065: 'shapes': undeclared identifier
<source>(1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
<source>(3): error C2146: syntax error: missing ';' before identifier 'cmake_minimum_required'
Execution build compiler returned: 2
```

### Expected behavior

Should compile like GCC , reproduceable across at least two different windows machines, firefox and chrome with multiple different versions. 

### Reproduction link

https://godbolt.org/#z:OYLghAFBqd5QCxAFwE4FN0BoCWIIDGAtgIYDW6AgqsAM4gDkAtACIDCAspQNICiA%2BgCEAqgEkAMi34AVAJoAFXgFIAzCwBK6ADYB1HMgQt0AI1EA7AGYB7BlgJWiABxxb0qcSTPAAriWDpRABMQAiUAJkFwwTtvWmQHAHlvZEdkgDEXdDMSInQQWgQSR3RaAEdfDCwLTPpYdED9K1QgkCYARirMloBOTtds3PzC4toAegIcVAJXADoELFAGcJVHVD9SAGorMwJ0JQAGSgOjsJUcHa1vQPQN8LDz5DcLEl3aObvj4%2BmSWloNtkm0zyG1Sxi0OAIG1EAGVhjclAB2SKHVY4ABuJEeIGOG1xGweGzWDViqmRlFB4II2MOeP%2BgNcEAJRJwsQAlKTPjS8QTaN5UM9dvxaDgAF7oCCsjb2MxxLZotyoHDXDmHREsFWUWw4WjmaZXeqMfZa2gcEjnaFWPm7RhtY0JYpmG22LSeYAtUIRKKsrAQeqNZrBdp9ALBNr7YMDPIFIolUYPJ4vEpzBaMZardYkLY7Paqw7fX5Q2Ex25I44UiHUyi0tGTZC%2BLT4szIDa8/mJoWi8WS6Wy1QsDb7DVqjXG3WXa7BBhG3Ams1mC1WvIMW0z%2B1ZJ1YF1ed1RL0%2Bv3xAOtDrVVwtNonzKRoYxsYYAjIV2zeaLNNrYCbba7TknM4XfW3GE9xNgmrzvEBP75n8mgPk%2BwLlpCMJwiWZKohiWI4tyTYbP0wAGBqCGVrSMGPl4DIErhBjsioZKYbiPJ8gK6AdmKEpStsspWPKqCKsqNGfAi6r8Yco7/hOhrGqa5qWlMS4rtqa6OsuzqujunoRN6voNIeLRhMG556aeWQ5FGcJjBMUyzAQjiOCmSynOcerXIBYQWUC4FhD%2BAKWXkIDeUCjLYcybIbCAhIkMStAQMFtCSoitGCT%2BBL%2Ba4ID5Ix7bCqxcWllyuIYHWqBmOFkUbAAVCVLJ/BVKhDolIkzmO%2BqTtO2pSfOMnWspq4OhJm6qcEHqRBp%2B7aU0LQqPpoaTUZ17RiMoz3qRwBWTZdnLI547wkBS1wR5P4kXBaWHWR4oUVkeEIJKYWUQgEC3TlCXqrmlAEidK2%2Ba2TEsV27Eys28V0YS6CFcVt3lThF34cJRz1ZqjViQaU6SXOC6yRuCm9cj/XboNu4jVp/otAAbFNIBtAALBGJkgKQ5wzNZtmLKJTlI61s7SYuGO0IpfVbm6k4MJpB7jaGZNtAArNTgycOQ6DiNqyBvMgAAeyB2asVgAFboA%2BEDzSU7IvcQcv8EQ5w4EQ3hEPwGDlJM9QQAAarw6jQqICQAHIbCoMwS0bRyHBFgT8OgKu68kJBguKBtlBUOZVnisfjPS6AMzZQPJ7tp3p44QN02YucB8cj40CD/DgmYZAVzgxhrIqJT62Z5QkBgQMWEQyCBAHLNbS1KOc%2Bj2OY%2Bu2P8%2B6pAUMLY1HkGRnnqTs00xgtCdbGCDaFoVgzKr6uvocAASm9WFgGwAO5NFogRgGAP5MPfTDHNIG8bLwZiBMcvfNX1bWo2v3O826uPPG6lBDTyJoGS8Z5QwImlnkZILgxhGVRCBVAyZXynHTB%2BTMX4E6fAcojW4Kg2BxEVF4fgNZ0Bn1UMoY2LoCwZFcPIMhjxUAoTLN4MEFZM6PmQBCDYaIrBKg2BvLQW9CAcWbAQQobCypL1yNRJ6I4Eas37jOdqaMuryR5ljFcwCQj4zAaNCBIAqbz1DAADjgSABBWgkGZBQaw3O60CGsxcsglhbh9ovQ2oQ1QJC0DnGADQ/Bf43H%2BIsKQ9AOQQmqlcVtIhAIrBRJiSoWhgdKCCOEY4/gojxE9ikTI8q8j0CPR4cEfIgSvA4XOHsGG5S0o4EiWgaJRANgWA1LSCwMwrAOggCUxRQMz4IEyBsfWXc0r%2BGQJXcUFhT4zNZGUvKtIWwTJCJaAGxD/E1LMPCLZxCNhgCWBLNgZgjmdLxMOZZ3TpjJK7HVZ68NtRNXEsPDmHUubdRHkpac%2Bihpem9NqWWFBmHa11sgPqWtyZYF2WfRhIZybdG9FoRgEtbA/NsFYRg0gMDbRUCuCFyNFlYDICAMI%2Bw/YSwlhYimxMLEIm6N0NoxMOgooYBTdFfUsUMFsPQcMhKjSaRgFAYVEAkD2GuLwGeuB8AlNpnOZx1gmzQgICQVKlMqjbGQMIWg6B5Aq0hSAUm/MDGgKwLq1wD4cDbHwFkQIbArCXCII6DodqFa7M9tbYwbgyW9EcMk/Q1qzAOqdS6rA/rhR8O2O69AnqiDetQL6812hwVBuhKXZAIbrZhotam7Y6bW7IBjXGhNSa4iFqzc66F5bUBFtqSWn1YQkXmv/vZMJCSImd3GE0NOCBYm/k2gBO4yd4xtjAn2iCcT21DqAlncFe0J2eSnYO5yw6zIpx8t4gdfigK2Psa4RxXjF1JWwryIg0JOxRQKYWZCZVtjYD%2BrKJCxYyrIAvksxO%2BUQZ8mKvex%2BaSvqZU7GxKIGw31WH/bwQDgosr3PqXDY4WTAgbECFYC0uQDBBMED8eoCQzDUDoIFZsrdgAEFPtI1u5UyokbRB%2B2kTSxkkchDQgcdGVm4nhcw0daU8lWAgDRpQEtBBtEEywQZyyrmw0eccAkUyL1imfkEqKbHcTvVcISCAYRxOfrpD5KUmntNAwKj%2Bls1t5ON3CMTVAp9LMEEMwhw4BIC5EY2Ex8jRSyrUZoLR9hyzUPoZBiMrw2HdWBDwwRqKbnXPecM8s4zRUNhyc7IprwymHmf2Raizl2MsUF2cQKoWPpxVWEldKvA/Srw02BfLRWys1aauVaq9VZitU6r1Qa7GULWWuhCJPbAuarU2t9O/StYa3X1q9Y28NAao3Bsddm6FEbA3Rom/GqbA3ZsFtraN6tKbBvzgzcWybia9I1szfNqtHQztHbWyd70q9Pmax1nrWOxc8x9bNhbK2Ns7beAdoEZ2rt3Zex9n7N7lBg6h3DgQSO0cm63hbm3ZZyc3KrTzsj9d2cPq5yBnu0YHjR04%2BWXlxm4PS5TJrlXGuddW44EbrHRHCcumd27hlzcWWYVcr8qaCgCs4h1fVgVzSxXSv%2BhlRV/oNMUep0VVqlVaq8gaqVdq3V%2BrDV6RNf8iIybLWzdtSNi7Y3343dLX6mbQadsdCW7Nk3PregbbTRmy3Ou80HcLbbxN9uneG%2BrYd1bpv7utt8eEoCqPe0fBeilXyUeXMxWupVWI0UIpVQ/ZJmT2Eo9pWg8xWDbFr2Azi9%2BhLMUIYl5qulkSmWGBos5zlm8C0w/5YksL9ZovDzi7lXjgnqDZeNYV%2BTFrTY2tq866YnGoAtfRAd0Nu1zvxseuO%2BTWB1uLc%2B6t%2BblbC/btL5d/trb53Q27d14793/ufVtFgWd5312z%2BJov4Hz5weO1AW70449Pj4lDuIaQoJ/an9f7YGaQwFSXSX/1XWIWtRSSID/0OCQw2E408UTRAF4wkX%2BilA8wGV8x0ziAqR/2qRmSHGRzWSaSgPaQuVxG6V6SyAl2MgUXIPPhGXU3GQqSmRmX6XmVqUWSwPY1xBwLSnsGSESW2RmSEIOXOROTOSWBhlpEky6QZi3l1QlAr01CrxrwxSwCxS7wcUQKbyJSK1b3QClTF3KzlTnVghzkZga2QHl2aysOHw62nChUmk10MV3z12G3tTXywHn1jUXzN0jVX0P3XwCM318O33tz20229yCLcJP1rQ9xAC9wrS8Jvy3wDxbUf0/1XR2nnRznfwyTU18kKJcwelCkhi8AMHuihiuiwLT0c2wkKKzwyhg2A27EkW4LxHizBmqIhlumUMKzZTUK5zMOWjRywCF29A3gih9QlBJVMWJhmApglhUG6H2H2ARH2G6DCDaG6AsWNUYA5SwCIBAAlnDHUO5V5RAH5Wbx9FFVFWKycEyGs3K3sEeNcETTREZgoR2IrkxBKGQH4BVmJipmuBrF2CdjpzPkARXFPFYXoAgGMD6mMHOFbgAE8NxkTshUBUSEhjBntCUVxXjcgmw8MtB0TsZrhSBTo%2BoGglp0QSg%2Bow4I4sRh4QI2Vfla565USHVrg%2BpAljjlJvQLAXQ6AISqFoTbBlcbDFdB8Vd2tDVnCetJ9Nxa5ahZjelZt6AeVYiZ8DcYifCG079psQi5sYiV9QjDSj9Xd99r9Ii4i600jz9zVoiFsrs/dHS79vQWlFdVDstpxuUNggSKYNgiBaBPiBEdiZgXRHhZQIAcVMBAJ8VWRbAJisApjrhE1ZjSVli/ZaVNitjViEQLF9g2gVAqY2VDjjiKYKUJYKYLEyz9haz6zqyJZSZzjGBLjri9C4BYAkB4hHVxcSMtTbAhz5BPBtBYQrAz4NxXjnB3iQBJoRZE1uopSmsZS7DVcHDbAiBtgXgrAjDDwD4fhBBMB8NkgrBFIkYVwdzsh7ADymgJSjjdz7B00GglIVwcDzgOznS3yxzdktBJyz53yUyrBHUWhHASAEBHVsBvToUz41hHAnRfTa9/TGAIKoKmC0BvAq44pTgVBz59AEBAy9imBgTEsCBIQwwZgVAUybixUQANlUh1YTC5c1yB8Nz5TR9JpvSlQ4KEKkL2dq8/TMVGAkgUhBCrALBAyyLQzwy0RIzoz/ixkHU3i3BEyVBkzxjm9JjokMz8Aq9KyyUFiLx6ywgWU2hTKWU9J2ztT6AOghdbj4B6KmSYd29ytRzxyAKoKgK%2BpZyXBMQg0/yJzvLgK7AHA5yfVgALw9I/L3ixLALQqXKIsQAV414xheMd56sXLXyvztTVz%2B8ldWtNzDVusvBTVhpohwRjA1SIBrwO51ZuJGAERSyhZvQNSg0tSmAcC%2BxJ9yUNgmAEh8KmBhT4heVW0Pyu5zggqvKpzQrYKOh4KigBLBjhKNDGBeBodzy2EVYSKyLSNKK2gZgwhlLXCNh4y8U2hNLUyKztyFzfYVAHrHqnqnqUKRLbKritKiVvRszfZaziZ8ym11jizSzyzGAaLXq1rtTUzSUGVFiKYKZJZ8VyV9h6ymVBKwhbqwwziucobtL0bVqLjPrBVvRuJhQbUKYgA

### Screenshots

Not applicable

**Comment by partouf** [comment] 2023-01-14 14:52
duplicate of https://github.com/compiler-explorer/compiler-explorer/issues/3216

Even though you can check the CMake button, the MSVC compiler does not actually support CMake yet, and it has never supported it as of yet.

It only supports multiple files in the sense of 1 `example.cpp` and header files or other files that don't need to be compiled.

(You can cheat a little by including the cpp files into `example.cpp`, but it's not exactly pretty. https://godbolt.org/z/3f1Gxrqen)

**Closed by partouf** 2023-01-14 14:52 UTC
Labels: bug
