### ISSUE TITLE
[LIB REQUEST] kotlinx.coroutines

### ISSUE THREAD

**Issue by chaoren** [compiler-explorer/compiler-explorer#6997] opened 2024-10-22 16:42 UTC
https://github.com/Kotlin/kotlinx.coroutines

`kotlinx.coroutines` is the standard library for Kotlin coroutines.

**Comment by junlarsen** [comment] 2024-10-23 01:33
Hi @chaoren thanks for showing interest in Kotlin libraries. We currently don't support libraries for any of the JVM languages, but if you are interested in looking into it we happily accept PRs!

(closing as duplicate of https://github.com/compiler-explorer/compiler-explorer/issues/5942)

**Closed by junlarsen** 2024-10-23 01:33 UTC
