### ISSUE TITLE
[BUG]: Lines with local labels in gcc inline assembly are silently skipped

### ISSUE THREAD

**Issue by jdx-gh** [compiler-explorer/compiler-explorer#4931] opened 2023-04-03 02:16 UTC
### Describe the bug

[Local labels](https://sourceware.org/binutils/docs/as/Symbol-Names.html) (i.e. those with names consisting of digits) are silently skipped in the output code. Tested with ARM gcc, but other gcc targets are also likely affected.

### Steps to reproduce

1. Visit godbolt.org
2. Paste following code into the source pane:
```
#define MTX_UNLOCKED 1
#define MTX_LOCKED 0

void lock(unsigned int *mtx)
{
    asm volatile(
        "mov r3, %1\n"
        "1:\tswp r3, r3, [%0]\n\t"
        "cmp r3, %1\n\t"
        "beq 1b"
    :
    : "r"(mtx), "i"(MTX_LOCKED)
    : "r3", "cc", "memory");
}

void lock2(unsigned int *mtx)
{
    asm volatile(
        "mov r3, %1\n"
        "1:\n\t"
        "swp r3, r3, [%0]\n\t"
        "cmp r3, %1\n\t"
        "beq 1b"
    :
    : "r"(mtx), "i"(MTX_LOCKED)
    : "r3", "cc", "memory");
}
```
3. Choose "ARM gcc 11.2.1 (none)" compiler
4. Add "-O3 -march=armv4t -pedantic -Wall -Wextra" to the compiler options
5. The output pane will show code without labels:
```
lock:
        mov r3, #0
        cmp r3, #0
        beq 1b
        bx      lr
lock2:
        mov r3, #0
        swp r3, r3, [r0]
        cmp r3, #0
        beq 1b
        bx      lr
```

### Expected behavior

The output pane should show code with local labels:
```
lock:
        mov r3, #0
1:	swp r3, r3, [r0]
        cmp r3, #0
        beq 1b
        bx      lr
lock2:
        mov r3, #0
1:
        swp r3, r3, [r0]
        cmp r3, #0
        beq 1b
        bx      lr
```

### Reproduction link

https://godbolt.org/z/jbrW9jMG6

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment] 2023-04-03 03:02
Possibly a duplicate of #2034 but this has more context

**Closed** 2023-11-11 12:56 UTC
Labels: bug
