### ISSUE TITLE
Add common Rust crates

### ISSUE THREAD

**Issue by dhouck** [compiler-explorer/compiler-explorer#2515] opened 2021-03-24 12:05 UTC
I'm new to Rust so can't make a list of all the ones people might expect.  I know I want:
 - [ ] https://crates.io/crates/contracts but don't expect most people to
 - [ ] https://crates.io/crates/rand, which seems likely to be relatively common.

**Comment by partouf** [comment] 2021-03-24 12:22
Duplicate of #754 and #1925

**Comment by RubenRBS** [comment] 2021-03-27 06:21
Hi, thanks for taking the time tu suggest us some useful crates!
As @partouf mentioned in the linked issues, this is something we currently don't support, but we're actively looking into (See releated issue). I've recorded your suggestion, and will close this as to try to keep everything crate releated in one place, but please, once support lands, feel free to add additional suggestions of crates :)

**Closed by RubenRBS** 2021-03-27 06:21 UTC
Labels: lang-rust, request
