### ISSUE TITLE
[BUG] Golang executor fails

### ISSUE THREAD

**Issue by kfsone** [compiler-explorer/compiler-explorer#2178] opened 2020-09-04 01:54 UTC
Attempting an executor on any golang code results in a complaint about a -L flag:
```
Could not execute the program

Compiler returned: 2

Compiler stderr

flag provided but not defined: -L.

usage: go build [-o output] [-i] [build flags] [packages]

Run 'go help build' for details.
```

**To Reproduce**
1. Enter a simple golang program (package main; import "fmt"; func main() { fmt.Println("Hello"); }
2. Add any go compiler.
3. Add an executor from the compiler.

**Expected behavior**
Expected to see program output, or a message indicating execution was blocked.

**Link**
https://godbolt.org/z/xvfsPx

**Comment by apmorton** [comment] 2020-09-04 02:10
Duplicate of #2051

**Closed by apmorton** 2020-09-04 02:10 UTC
Labels: bug

**Comment by partouf** [comment] 2020-09-05 14:00
We have changed some things to enable Go execution now for most of the compilers, and the compilers that can't are now no longer selectable from the execution pane.
