### ISSUE TITLE
[BUG]: Compile To Binary checkbox doesn't work on ARM Clang

### ISSUE THREAD

**Issue by Alcaro** [compiler-explorer/compiler-explorer#3327] opened 2022-02-05 22:27 UTC
### Describe the bug

Compile To Binary checkbox doesn't work on ARM Clang

### Steps to reproduce

1. Visit godbolt.org
2. Switch to an ARM Clang compiler
3. Enable Output -> Compile To Binary
4. Add an int main(){}

### Expected behavior

arm32 Clang should emit machine code, just like arm32 gcc does. (arm64 Clang has the same issue; arm64 gcc disables that checkbox.)

Actual behavior:

<No output: objdump returned 1>

### Reproduction link

https://godbolt.org/z/Wc8roaYav

### Screenshots

Not necessary

### Operating System

Lubuntu 21.10

### Browser version

Firefox 96

**Comment by dkm** [comment] 2022-02-07 18:05
Caused by bad config:
```
compiler.armv7-clang-trunk.objdumper=/opt/compiler-explorer/gcc-snapshot/bin/objdump
```

Not sure using native objdump is a good pick for ARM. I've seen similar error for cross ppc (where binary is currently disabled) and thought of this issue :) Will fix that later, easy one :D

**Comment by dkm** [comment] 2022-02-08 07:00
should be fixed when prod site is updated :)

**Closed by dkm** 2022-02-08 07:00 UTC
Labels: bug

**Comment by dkm** [comment] 2022-02-09 19:35
should be fixed :)
