### ISSUE TITLE
[BUG] Internal Compiler Explorer error: Error: spawn C:\data\msvc\14.29.30130.2-Pre\bin\Hostx64\x64\undname.exe ENOENT

### ISSUE THREAD

**Issue by hewillk** [compiler-explorer/compiler-explorer#2830] opened 2021-07-30 12:42 UTC
```
#include <type_traits>
auto x = std::declval<int>();
```

https://godbolt.org/z/oEGcaKo75

**Comment by OmegaMetroid** [comment] 2021-07-30 19:25
This occurs when any symbol is generated, and is indeed caused by undname specifically.  Until it's fixed, you can disable "Output > Demangle identifiers" as a workaround.

https://godbolt.org/z/jcbEsW4e4

**Comment by tiagomacarios** [comment] 2021-08-04 20:11
@mattgodbolt Seems to be fixed with the last update to the toolset done today in the morning.

**Comment by mattgodbolt** [comment] 2021-08-04 20:12
Fantastic! Thanks!

**Closed by mattgodbolt** 2021-08-04 20:12 UTC
Labels: MS/Windows, bug
