### ISSUE TITLE
[REQUEST] "Reset code and UI layout" button should honour my default language

### ISSUE THREAD

**Issue by brainplot** [compiler-explorer/compiler-explorer#1985] opened 2020-05-18 17:48 UTC
I'm using Compiler Explorer with Rust a lot these days and I have set Rust as my default language in the site settings. When I want to go back to a clean state and a clean buffer to type code in, I would hit the `Reset code and UI layout` button. I would expect to get a clean Rust buffer, same way as if I had clicked "Rust" in the drop-down menu, but I get a clean C++ buffer instead so I have to set it back to Rust every time.
I don't know if this is intended behaviour but it's a bit unintuitive to me, not to mention slightly annoying (although not a big deal by any means). Can the reset button honour the user preferences?

I'm very grateful for your work on the site. Thank you for this amazing tool!

**EDIT**: I just realized there's https://rust.godbolt.org which indeed does what I expect. Previously I was using just https://godbolt.org. Feel free to close this issue if it's intended behaviour :smile:

**Comment by partouf** [comment] 2020-05-18 19:03
I don't think this is intended behaviour, but I don't know if it's easy to fix either.

**Comment by brainplot** [comment] 2020-05-18 19:28
Next to the default language drop-down, in the settings, there's a little info icon you can hover over and it says:
> New editors only (Reset UI to clear yours)

It sounds like it _should_ work but it doesn't.

**Comment by RubenRBS** [comment] 2022-07-25 19:19
Hi. This was fixed a while ago (Or else I can't repo for some other reason) but we did not get around closing the issue, sorry!

**Closed by RubenRBS** 2022-07-25 19:19 UTC
Labels: ui, request
