### ISSUE TITLE
[BUG]: `abort()` calls get reported as seg faults in executed code

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#5376] opened 2023-08-11 15:25 UTC
### Describe the bug

When an executed program calls `abort()` the actual error reported is SEGFAULT.

### Steps to reproduce

1. Call `abort()` in a program
2. Observe the output says
```
Program returned: 139
Program terminated with signal: SIGSEGV
```

### Expected behavior

Something like:
```
Program returned: 138
Program terminated with signal: SIGABRT
```

### Reproduction link

https://godbolt.org/z/6s9Y3YPqe

### Screenshots

Not applicable

**Comment by partouf** [comment] 2023-08-11 15:43
duplicate of https://github.com/compiler-explorer/compiler-explorer/issues/5224

**Comment by mattgodbolt** [comment] 2023-08-11 15:43
Oh shucks. Thanks partouf

**Closed by partouf** 2023-08-11 15:43 UTC
Labels: bug
